<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Rating Scale Model | Rasch Measurement Theory Analysis in R: Illustrations and Practical Guidance for Researchers and Practitioners</title>
  <meta name="description" content="The purpose of this book is to illustrate techniques for conducting Rasch measurement theory analyses using existing R packages. The book includes some background information about Rasch models, and the primary objective is to demonstrate how to apply the models to data using existing R packages and how to interpret the results. The intended audience for this book is graduate students or professionals who have a basic familiarity with Rasch measurement theory and who have a basic working knowledge of the R software." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Rating Scale Model | Rasch Measurement Theory Analysis in R: Illustrations and Practical Guidance for Researchers and Practitioners" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The purpose of this book is to illustrate techniques for conducting Rasch measurement theory analyses using existing R packages. The book includes some background information about Rasch models, and the primary objective is to demonstrate how to apply the models to data using existing R packages and how to interpret the results. The intended audience for this book is graduate students or professionals who have a basic familiarity with Rasch measurement theory and who have a basic working knowledge of the R software." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Rating Scale Model | Rasch Measurement Theory Analysis in R: Illustrations and Practical Guidance for Researchers and Practitioners" />
  
  <meta name="twitter:description" content="The purpose of this book is to illustrate techniques for conducting Rasch measurement theory analyses using existing R packages. The book includes some background information about Rasch models, and the primary objective is to demonstrate how to apply the models to data using existing R packages and how to interpret the results. The intended audience for this book is graduate students or professionals who have a basic familiarity with Rasch measurement theory and who have a basic working knowledge of the R software." />
  

<meta name="author" content="Stefanie A. Wind &amp; Cheng Hua" />


<meta name="date" content="2021-08-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="MD-fit.html"/>
<link rel="next" href="PC-model.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Rasch R Book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#overview-of-rasch-measurement-theory"><i class="fa fa-check"></i><b>1.1</b> Overview of Rasch Measurement Theory</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#online-resources"><i class="fa fa-check"></i><b>1.2</b> Online Resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html"><i class="fa fa-check"></i><b>2</b> Dichotomous Rasch Model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#example-data-transitive-reasoning-test"><i class="fa fa-check"></i><b>2.1</b> Example Data: Transitive Reasoning Test</a></li>
<li class="chapter" data-level="2.2" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#dichotomous-rasch-model-analysis-with-cmle-in-erm"><i class="fa fa-check"></i><b>2.2</b> Dichotomous Rasch Model Analysis with CMLE in eRm</a></li>
<li class="chapter" data-level="2.3" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#dichotomous-rasch-model-analysis-with-mmle-in-tam"><i class="fa fa-check"></i><b>2.3</b> Dichotomous Rasch Model Analysis with MMLE in TAM</a></li>
<li class="chapter" data-level="2.4" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#dichotomous-rasch-model-analysis-with-jmle-in-tam"><i class="fa fa-check"></i><b>2.4</b> Dichotomous Rasch Model Analysis with JMLE in TAM</a></li>
<li class="chapter" data-level="2.5" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#example-results-section"><i class="fa fa-check"></i><b>2.5</b> Example Results Section</a></li>
<li class="chapter" data-level="2.6" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#exercise"><i class="fa fa-check"></i><b>2.6</b> Exercise</a></li>
<li class="chapter" data-level="2.7" data-path="Dich-Rasch-model.html"><a href="Dich-Rasch-model.html#supplementary-learning-materials"><i class="fa fa-check"></i><b>2.7</b> Supplementary Learning Materials</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="MD-fit.html"><a href="MD-fit.html"><i class="fa fa-check"></i><b>3</b> Evaluating the Quality of Measures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="MD-fit.html"><a href="MD-fit.html#evaluating-measurement-quality-from-the-perspective-of-rasch-measurement-theory"><i class="fa fa-check"></i><b>3.1</b> Evaluating Measurement Quality from the Perspective of Rasch Measurement Theory</a></li>
<li class="chapter" data-level="3.2" data-path="MD-fit.html"><a href="MD-fit.html#example-data-transitive-reasoning-test-1"><i class="fa fa-check"></i><b>3.2</b> Example Data: Transitive Reasoning Test</a></li>
<li class="chapter" data-level="3.3" data-path="MD-fit.html"><a href="MD-fit.html#rasch-model-fit-analysis-with-cmle-in-erm"><i class="fa fa-check"></i><b>3.3</b> Rasch Model Fit Analysis with CMLE in <em>eRm</em></a></li>
<li class="chapter" data-level="3.4" data-path="MD-fit.html"><a href="MD-fit.html#graphical-displays-for-evaluating-model-data-fit"><i class="fa fa-check"></i><b>3.4</b> Graphical Displays for Evaluating Model-Data Fit</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="MD-fit.html"><a href="MD-fit.html#reliability"><i class="fa fa-check"></i><b>3.4.1</b> Reliability</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="MD-fit.html"><a href="MD-fit.html#rasch-model-fit-analysis-with-mmle-in-tam"><i class="fa fa-check"></i><b>3.5</b> Rasch Model Fit Analysis with MMLE in TAM</a></li>
<li class="chapter" data-level="3.6" data-path="MD-fit.html"><a href="MD-fit.html#rasch-model-fit-analysis-with-jmle-in-tam"><i class="fa fa-check"></i><b>3.6</b> Rasch Model Fit Analysis with JMLE in TAM</a></li>
<li class="chapter" data-level="3.7" data-path="MD-fit.html"><a href="MD-fit.html#exercise-1"><i class="fa fa-check"></i><b>3.7</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="RS-model.html"><a href="RS-model.html"><i class="fa fa-check"></i><b>4</b> Rating Scale Model</a>
<ul>
<li class="chapter" data-level="4.1" data-path="RS-model.html"><a href="RS-model.html#example-data-liking-for-science"><i class="fa fa-check"></i><b>4.1</b> Example Data: Liking for Science</a></li>
<li class="chapter" data-level="4.2" data-path="RS-model.html"><a href="RS-model.html#rsm-analysis-with-cmle-in-erm"><i class="fa fa-check"></i><b>4.2</b> RSM Analysis with CMLE in <em>eRm</em></a></li>
<li class="chapter" data-level="4.3" data-path="RS-model.html"><a href="RS-model.html#rsm-analysis-with-mmle-in-tam"><i class="fa fa-check"></i><b>4.3</b> RSM Analysis with MMLE in <em>TAM</em></a></li>
<li class="chapter" data-level="4.4" data-path="RS-model.html"><a href="RS-model.html#rsm-analysis-with-jmle-in-tam"><i class="fa fa-check"></i><b>4.4</b> RSM Analysis with JMLE in TAM</a></li>
<li class="chapter" data-level="4.5" data-path="RS-model.html"><a href="RS-model.html#example-results-section-1"><i class="fa fa-check"></i><b>4.5</b> Example Results Section</a></li>
<li class="chapter" data-level="4.6" data-path="RS-model.html"><a href="RS-model.html#exercise-2"><i class="fa fa-check"></i><b>4.6</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="PC-model.html"><a href="PC-model.html"><i class="fa fa-check"></i><b>5</b> Partial Credit Model</a>
<ul>
<li class="chapter" data-level="5.1" data-path="PC-model.html"><a href="PC-model.html#example-data-liking-for-science-1"><i class="fa fa-check"></i><b>5.1</b> Example Data: Liking for Science</a></li>
<li class="chapter" data-level="5.2" data-path="PC-model.html"><a href="PC-model.html#pcm-analysis-with-cmle-in-erm"><i class="fa fa-check"></i><b>5.2</b> PCM Analysis with CMLE in eRm</a></li>
<li class="chapter" data-level="5.3" data-path="PC-model.html"><a href="PC-model.html#summarize-the-results-in-tables"><i class="fa fa-check"></i><b>5.3</b> Summarize the Results in Tables</a></li>
<li class="chapter" data-level="5.4" data-path="PC-model.html"><a href="PC-model.html#pcm-application-with-mmle-in-tam"><i class="fa fa-check"></i><b>5.4</b> PCM Application with MMLE in TAM</a></li>
<li class="chapter" data-level="5.5" data-path="PC-model.html"><a href="PC-model.html#pcm-application-with-jmle-in-tam"><i class="fa fa-check"></i><b>5.5</b> PCM Application with JMLE in TAM</a></li>
<li class="chapter" data-level="5.6" data-path="PC-model.html"><a href="PC-model.html#example-results-section-2"><i class="fa fa-check"></i><b>5.6</b> Example results section</a></li>
<li class="chapter" data-level="5.7" data-path="PC-model.html"><a href="PC-model.html#exercise-3"><i class="fa fa-check"></i><b>5.7</b> Exercise</a></li>
<li class="chapter" data-level="5.8" data-path="PC-model.html"><a href="PC-model.html#bibliography"><i class="fa fa-check"></i><b>5.8</b> Bibliography</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="MFR-model.html"><a href="MFR-model.html"><i class="fa fa-check"></i><b>6</b> Many Facet Rasch Model</a>
<ul>
<li class="chapter" data-level="6.1" data-path="MFR-model.html"><a href="MFR-model.html#running-the-mfrm-with-wide-format-data-in-tam-package"><i class="fa fa-check"></i><b>6.1</b> Running the MFRM with Wide-Format Data in TAM Package</a></li>
<li class="chapter" data-level="6.2" data-path="MFR-model.html"><a href="MFR-model.html#example-2-running-pc-mfrm-with-long-format-data-using-the-tam-package"><i class="fa fa-check"></i><b>6.2</b> Example 2: Running PC-MFRM with Long-Format Data using the TAM Package</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="MFR-model.html"><a href="MFR-model.html#specify-the-pc-mfrm"><i class="fa fa-check"></i><b>6.2.1</b> Specify the PC-MFRM:</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="MFR-model.html"><a href="MFR-model.html#notes-on-formulations-for-many-facet-rasch-models"><i class="fa fa-check"></i><b>6.3</b> Notes on Formulations for Many-Facet Rasch Models</a></li>
<li class="chapter" data-level="6.4" data-path="MFR-model.html"><a href="MFR-model.html#example-results-section-3"><i class="fa fa-check"></i><b>6.4</b> Example Results Section</a></li>
<li class="chapter" data-level="6.5" data-path="MFR-model.html"><a href="MFR-model.html#exercise-4"><i class="fa fa-check"></i><b>6.5</b> Exercise</a></li>
<li class="chapter" data-level="6.6" data-path="MFR-model.html"><a href="MFR-model.html#bibliography-1"><i class="fa fa-check"></i><b>6.6</b> Bibliography</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="DIF.html"><a href="DIF.html"><i class="fa fa-check"></i><b>7</b> Basics of Differential Item Functioning</a>
<ul>
<li class="chapter" data-level="7.1" data-path="DIF.html"><a href="DIF.html#detecting-differential-item-functioning-in-r-for-dichotomous-items"><i class="fa fa-check"></i><b>7.1</b> Detecting Differential Item Functioning in R for Dichotomous Items</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="DIF.html"><a href="DIF.html#example-data-transitive-reasoning"><i class="fa fa-check"></i><b>7.1.1</b> Example Data: Transitive Reasoning</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="DIF.html"><a href="DIF.html#detecting-differential-item-functioning-in-r-for-polytomous-items"><i class="fa fa-check"></i><b>7.2</b> Detecting Differential Item Functioning in R for Polytomous Items</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="DIF.html"><a href="DIF.html#example-data-style-ratings"><i class="fa fa-check"></i><b>7.2.1</b> Example Data: Style Ratings</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="DIF.html"><a href="DIF.html#exercise-5"><i class="fa fa-check"></i><b>7.3</b> Exercise</a></li>
<li class="chapter" data-level="7.4" data-path="DIF.html"><a href="DIF.html#references-these-need-to-be-updated"><i class="fa fa-check"></i><b>7.4</b> References [these need to be updated!]</a></li>
<li class="chapter" data-level="7.5" data-path="DIF.html"><a href="DIF.html#resources-for-further-study"><i class="fa fa-check"></i><b>7.5</b> Resources for Further Study</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="RS-Eval.html"><a href="RS-Eval.html"><i class="fa fa-check"></i><b>8</b> Rating Scale Evaluation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="RS-Eval.html"><a href="RS-Eval.html#what-is-rating-scale-evaluation"><i class="fa fa-check"></i><b>8.1</b> What is Rating Scale Evaluation?</a></li>
<li class="chapter" data-level="8.2" data-path="RS-Eval.html"><a href="RS-Eval.html#r-lab-rating-scale-analysis-on-example-survey-data"><i class="fa fa-check"></i><b>8.2</b> R-lab: Rating Scale Analysis on Example Survey Data</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="RS-Eval.html"><a href="RS-Eval.html#load-and-investigate-the-data-set"><i class="fa fa-check"></i><b>8.2.1</b> Load and investigate the data set</a></li>
<li class="chapter" data-level="8.2.2" data-path="RS-Eval.html"><a href="RS-Eval.html#run-the-partial-credit-model"><i class="fa fa-check"></i><b>8.2.2</b> Run the Partial Credit Model</a></li>
<li class="chapter" data-level="8.2.3" data-path="RS-Eval.html"><a href="RS-Eval.html#check-categories-for-monotonicity"><i class="fa fa-check"></i><b>8.2.3</b> Check Categories for Monotonicity</a></li>
<li class="chapter" data-level="8.2.4" data-path="RS-Eval.html"><a href="RS-Eval.html#examine-category-probability-curves"><i class="fa fa-check"></i><b>8.2.4</b> Examine Category Probability curves</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="RS-Eval.html"><a href="RS-Eval.html#example-apa-format-results-section-for-rating-scale-analysis"><i class="fa fa-check"></i><b>8.3</b> Example APA-format Results section for rating scale analysis</a></li>
<li class="chapter" data-level="8.4" data-path="RS-Eval.html"><a href="RS-Eval.html#references"><i class="fa fa-check"></i><b>8.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="Ref1.html"><a href="Ref1.html"><i class="fa fa-check"></i><b>9</b> References &amp; Other Good Stuff</a>
<ul>
<li class="chapter" data-level="9.1" data-path="Ref1.html"><a href="Ref1.html#rasch-glossary"><i class="fa fa-check"></i><b>9.1</b> Rasch Glossary</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="Ref1.html"><a href="Ref1.html#rasch-models"><i class="fa fa-check"></i><b>9.1.1</b> Rasch Models</a></li>
<li class="chapter" data-level="9.1.2" data-path="Ref1.html"><a href="Ref1.html#diagnostic-and-exploratory-rasch-figures"><i class="fa fa-check"></i><b>9.1.2</b> Diagnostic and Exploratory Rasch Figures</a></li>
<li class="chapter" data-level="9.1.3" data-path="Ref1.html"><a href="Ref1.html#estimation-methods-and-estimates"><i class="fa fa-check"></i><b>9.1.3</b> Estimation methods and Estimates</a></li>
<li class="chapter" data-level="9.1.4" data-path="Ref1.html"><a href="Ref1.html#popular-r-packages-for-running-rasch-model"><i class="fa fa-check"></i><b>9.1.4</b> Popular R-Packages for running Rasch Model</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="Ref1.html"><a href="Ref1.html#rasch-friendly-jounrals"><i class="fa fa-check"></i><b>9.2</b> <span>Rasch friendly Jounrals</span></a></li>
<li class="chapter" data-level="9.3" data-path="Ref1.html"><a href="Ref1.html#rasch-model-application-tempaltes"><i class="fa fa-check"></i><b>9.3</b> Rasch Model Application Tempaltes</a></li>
<li class="chapter" data-level="9.4" data-path="Ref1.html"><a href="Ref1.html#reference-for-this-book"><i class="fa fa-check"></i><b>9.4</b> Reference for this book</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Rasch Measurement Theory Analysis in R: Illustrations and Practical Guidance for Researchers and Practitioners</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="RS_model" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Rating Scale Model</h1>
<p>This chapter provides a basic overview of the Rasch Rating Scale Model (RSM) <span class="citation">(<a href="#ref-Rating_Form" role="doc-biblioref">Andrich 1978</a>)</span>, along with guidance for analyzing data with the RSM using R <span class="citation">(<a href="#ref-R-base" role="doc-biblioref">R Core Team 2019</a>)</span>. We use an example data set that includes participant responses to an attitude survey to illustrate the analysis using Conditional Maximum Likelihood Estimation (CMLE) via the <em>eRm</em> package <span class="citation">(<a href="#ref-eRm" role="doc-biblioref">Mair, Hatzinger, and Maier 2021</a>)</span>. We also demonstrate RSM analyses using Marginal Maximum Likelihood Estimation (MMLE) and Joint Maximum Likelihood Estimation (JMLE) via the <em>TAM</em> package <span class="citation">(<a href="#ref-TAM" role="doc-biblioref">Robitzsch, Kiefer, and Wu 2021</a>)</span>. After the analyses are complete, we present an example description of the results. The chapter concludes with a challenge exercise.</p>
<p><strong><em>Overview of the Rating Scale Model</em></strong></p>
<p>Andrich <span class="citation"><a href="#ref-Rating_Form" role="doc-biblioref">Andrich</a> (<a href="#ref-Rating_Form" role="doc-biblioref">1978</a>)</span> proposed the RSM (sometimes also called the Polytomous Rasch model) as an extension of the dichotomous Rasch model (see Chapter 2) for use with ordinal item responses that are scored in more than two categories (e.g., data from attitude scales or performance assessments). Like the dichotomous Rasch model, the RSM provides estimates of <em>person locations</em> and <em>item locations</em> on a log-odds scale that represents the latent variable. The RSM also provides estimates of <em>rating scale category thresholds</em> that reflect the difficulty associated with each pair of adjacent categories in the rating scale. Specifically, the RSM specifies the probability for a rating in category <em>k</em> rather than in category <em>k</em> - 1 as a function of the difference between person locations, item locations, and the location of the rating scale category threshold for category <em>k</em> on the logit scale.</p>
<p>The RSM can be stated in log-odds form as follows:</p>
<p><span class="math display">\[\begin{equation}\tag{4.1} ln\left[\frac{P_{n_i(x=k)}}{P_{n_i(x=k-1)}}\right]=\theta_{n}-\delta_{i}-\tau_{k} \end{equation}\]</span></p>
<p>In the RSM, <span class="math inline">\(\theta\)</span> is the person’s ability, <span class="math inline">\(\delta\)</span> is the item’s difficulty, and <span class="math inline">\(\tau\)</span> is the rating scale category threshold. In the RSM, the threshold is the location on the logit scale at which there is an equal probability for a rating in category <span class="math inline">\(k\)</span> and category <span class="math inline">\(k - 1\)</span>. For a rating scale made up of <span class="math inline">\(m\)</span> categories, there are <span class="math inline">\(m - 1\)</span> rating scale category thresholds.</p>
<p>The RSM produces one common set of rating scale category thresholds that apply to all of the items in the analysis. As a result, the RSM requires that the responses to all of the items include observations in the same categories. In addition, this common set of thresholds implies that the rating scale categories have a consistent interpretation across items. For example, for items with a four-category rating scale where 0 = <em>Strongly Disagree</em>, 1 = <em>Disagree</em>, 2 = <em>Agree</em>, and 3 = <em>Strongly Agree</em>, the RSM would produce a common set of three thresholds for all of the items. This common set of thresholds implies that the difference in the level of the latent variable required to provide a rating of <em>Strongly Agree</em> and <em>Agree</em> is the same for all of the items included in the analysis.</p>
<p><strong><em>Rating Scale Model Requirements</em></strong></p>
<p>Because it is a Rasch model, the RSM is based on the same requirements of unidimensionality, local independence, and invariance that we discussed in Chapter 2 for the dichotomous Rasch model. Evidence that rating scale responses approximate these requirements provides support for the meaningful interpretation and use of person, item, and threshold estimates on the logit scale as indicators of their respective on the latent variable. In practice, many analysts evaluate some or all of these requirements using various indicators of model-data fit. In the current chapter, we provide code for calculating some popular residual-based fit indices for items and persons. Readers can use the same techniques that we considered in Chapter 3 to evaluate fit to the RSM. In addition, readers can use rating scale analysis techniques to consider additional issues related to rating scale functioning; we discuss these methods in detail in next Chapter.</p>
<div id="example-data-liking-for-science" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Example Data: Liking for Science</h2>
<p>The example data for this chapter is a group of 75 children’s responses to the 25-item <em>Liking for Science</em> questionnaire, which was designed to measure their attitudes toward science activities. The data were published in <span class="citation"><a href="#ref-RS_analysis" role="doc-biblioref">Wright and Masters</a> (<a href="#ref-RS_analysis" role="doc-biblioref">1982</a>)</span>. Each item stem included a science activity, and three response options: 0 = <em>Dislike</em>, 1 = <em>Not Sure/Don’t Care</em>, and 2 = <em>Like</em>, such that responses in higher categories indicated more-favorable attitudes toward science activities.</p>
</div>
<div id="rsm-analysis-with-cmle-in-erm" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> RSM Analysis with CMLE in <em>eRm</em></h2>
<p>In the next section, we provide a step-by-step demonstration of a RSM analysis using the <em>Extended Rasch Modeling</em>, or <em>eRm</em> package <span class="citation">(<a href="#ref-eRm" role="doc-biblioref">Mair, Hatzinger, and Maier 2021</a>)</span>, which uses Conditional Maximum Likelihood Estimation (CMLE). We encourage readers to use the example data set that is provided in the online supplement to conduct the analysis along with us.</p>
<p><strong><em>Prepare for the Analyses</em></strong></p>
<p>We selected <em>eRm</em> for the first illustration in the current chapter because it includes functions for applying the RSM that are relatively straightforward to use and interpret. Please note that the <em>eRm</em> package uses the Conditional Maximum Likelihood Estimation (CMLE) method to estimate Rasch model parameters. As a result, estimates from the <em>eRm</em> package are not directly comparable to estimates obtained using other estimation methods.</p>
<p>To get started with the <em>eRm</em> package, view the citation information, and then install and load it into your R environment using the following code.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="RS-model.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>(<span class="st">&quot;eRm&quot;</span>)</span>
<span id="cb1-2"><a href="RS-model.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;eRm&quot;)</span></span>
<span id="cb1-3"><a href="RS-model.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;eRm&quot;</span>)</span></code></pre></div>
<p>Now that we have installed and loaded the packages to our R session, we are ready to import the data. We will use the function <code>read.csv()</code> to import the comma-separated values (.csv) file that contains the Liking for Science survey data. We encourage readers to use their preferred method for importing data files into R or R Studio.</p>
<p>Please note that if you use <code>read.csv()</code> you will need to specify the file path to the location at which the data file is stored on your computer or set your working directory to the folder in which you have saved the data.</p>
<p>First, we will import the data using <code>read.csv()</code> and store it in an object called <code>science.</code></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="RS-model.html#cb2-1" aria-hidden="true" tabindex="-1"></a>science <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;liking_for_science.csv&quot;</span>)</span></code></pre></div>
<p>Next, we will explore the data using descriptive statistics using the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="RS-model.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(science)</span></code></pre></div>
<pre><code>##     student           i1              i2              i3       
##  Min.   : 1.0   Min.   :0.000   Min.   :0.000   Min.   :0.000  
##  1st Qu.:19.5   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000  
##  Median :38.0   Median :1.000   Median :2.000   Median :1.000  
##  Mean   :38.0   Mean   :1.453   Mean   :1.547   Mean   :1.173  
##  3rd Qu.:56.5   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :75.0   Max.   :2.000   Max.   :2.000   Max.   :2.000  
##        i4               i5               i6              i7      
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.00  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:1.000   1st Qu.:0.00  
##  Median :1.0000   Median :0.0000   Median :1.000   Median :1.00  
##  Mean   :0.6933   Mean   :0.4933   Mean   :1.213   Mean   :0.92  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:1.50  
##  Max.   :2.0000   Max.   :2.0000   Max.   :2.000   Max.   :2.00  
##        i8             i9             i10             i11             i12       
##  Min.   :0.00   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :1.000  
##  1st Qu.:0.00   1st Qu.:0.000   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:2.000  
##  Median :1.00   Median :1.000   Median :2.000   Median :2.000   Median :2.000  
##  Mean   :0.72   Mean   :1.067   Mean   :1.733   Mean   :1.613   Mean   :1.827  
##  3rd Qu.:1.00   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :2.00   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000  
##       i13             i14             i15            i16             i17       
##  Min.   :0.000   Min.   :0.000   Min.   :0.00   Min.   :0.000   Min.   :0.000  
##  1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.00   1st Qu.:1.000   1st Qu.:1.000  
##  Median :2.000   Median :1.000   Median :2.00   Median :1.000   Median :1.000  
##  Mean   :1.693   Mean   :1.173   Mean   :1.48   Mean   :1.107   Mean   :1.267  
##  3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.00   3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :2.000   Max.   :2.000   Max.   :2.00   Max.   :2.000   Max.   :2.000  
##       i18             i19            i20              i21       
##  Min.   :0.000   Min.   :0.00   Min.   :0.0000   Min.   :0.000  
##  1st Qu.:2.000   1st Qu.:2.00   1st Qu.:0.0000   1st Qu.:1.000  
##  Median :2.000   Median :2.00   Median :1.0000   Median :2.000  
##  Mean   :1.933   Mean   :1.88   Mean   :0.6667   Mean   :1.587  
##  3rd Qu.:2.000   3rd Qu.:2.00   3rd Qu.:1.0000   3rd Qu.:2.000  
##  Max.   :2.000   Max.   :2.00   Max.   :2.0000   Max.   :2.000  
##       i22             i23            i24             i25       
##  Min.   :0.000   Min.   :0.00   Min.   :0.000   Min.   :0.000  
##  1st Qu.:1.000   1st Qu.:0.00   1st Qu.:1.000   1st Qu.:1.000  
##  Median :1.000   Median :0.00   Median :2.000   Median :1.000  
##  Mean   :1.293   Mean   :0.56   Mean   :1.427   Mean   :1.133  
##  3rd Qu.:2.000   3rd Qu.:1.00   3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :2.000   Max.   :2.00   Max.   :2.000   Max.   :2.000</code></pre>
<p>From the summary of <code>science</code>, we can see there are no missing data. We can also get a general sense of the scales, range, and distribution of each variable in the data set.</p>
<p>We can see that Student ID numbers range from 1 to 75, and that the maximum rating on the items was <em>x</em> = 2. Importantly, we can see that for item 12, the minimum rating was <em>x</em> = 1, and no ratings in the first category (<em>x</em> = 0) were observed in our sample. To use the RSM with these data, we will need to omit item 12 from our analysis. We will revisit these data in Chapter 5, where we include item 12 in a Partial Credit Model analysis. For now, we will create a new object called <code>science_drop_i12</code> that includes the Liking for Science data without item 12.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="RS-model.html#cb5-1" aria-hidden="true" tabindex="-1"></a>science_drop_i12 <span class="ot">&lt;-</span> <span class="fu">subset</span>(science, <span class="at">select =</span> <span class="sc">-</span>i12)</span></code></pre></div>
<p><strong><em>Run the Rating Scale Model</em></strong></p>
<p>Next we need to isolate the item response matrix from the descriptive variables in the data (in this case, student IDs). To do this, we will create an object made up of only the item responses by removing the first variable (<code>student</code>) from the data.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="RS-model.html#cb6-1" aria-hidden="true" tabindex="-1"></a>science.responses <span class="ot">&lt;-</span> <span class="fu">subset</span>(science_drop_i12, <span class="at">select =</span> <span class="sc">-</span>student)</span></code></pre></div>
<p>We will use <code>summary()</code> to calculate descriptive statistics for the <code>science.responses</code> object to check our work and ensure that the responses are ready for analysis:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="RS-model.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(science.responses)</span></code></pre></div>
<pre><code>##        i1              i2              i3              i4        
##  Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.0000  
##  1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:0.0000  
##  Median :1.000   Median :2.000   Median :1.000   Median :1.0000  
##  Mean   :1.453   Mean   :1.547   Mean   :1.173   Mean   :0.6933  
##  3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:1.0000  
##  Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.0000  
##        i5               i6              i7             i8             i9       
##  Min.   :0.0000   Min.   :0.000   Min.   :0.00   Min.   :0.00   Min.   :0.000  
##  1st Qu.:0.0000   1st Qu.:1.000   1st Qu.:0.00   1st Qu.:0.00   1st Qu.:0.000  
##  Median :0.0000   Median :1.000   Median :1.00   Median :1.00   Median :1.000  
##  Mean   :0.4933   Mean   :1.213   Mean   :0.92   Mean   :0.72   Mean   :1.067  
##  3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:1.50   3rd Qu.:1.00   3rd Qu.:2.000  
##  Max.   :2.0000   Max.   :2.000   Max.   :2.00   Max.   :2.00   Max.   :2.000  
##       i10             i11             i13             i14             i15      
##  Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.00  
##  1st Qu.:2.000   1st Qu.:1.000   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.00  
##  Median :2.000   Median :2.000   Median :2.000   Median :1.000   Median :2.00  
##  Mean   :1.733   Mean   :1.613   Mean   :1.693   Mean   :1.173   Mean   :1.48  
##  3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.00  
##  Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.00  
##       i16             i17             i18             i19      
##  Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.00  
##  1st Qu.:1.000   1st Qu.:1.000   1st Qu.:2.000   1st Qu.:2.00  
##  Median :1.000   Median :1.000   Median :2.000   Median :2.00  
##  Mean   :1.107   Mean   :1.267   Mean   :1.933   Mean   :1.88  
##  3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.00  
##  Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.00  
##       i20              i21             i22             i23      
##  Min.   :0.0000   Min.   :0.000   Min.   :0.000   Min.   :0.00  
##  1st Qu.:0.0000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:0.00  
##  Median :1.0000   Median :2.000   Median :1.000   Median :0.00  
##  Mean   :0.6667   Mean   :1.587   Mean   :1.293   Mean   :0.56  
##  3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:1.00  
##  Max.   :2.0000   Max.   :2.000   Max.   :2.000   Max.   :2.00  
##       i24             i25       
##  Min.   :0.000   Min.   :0.000  
##  1st Qu.:1.000   1st Qu.:1.000  
##  Median :2.000   Median :1.000  
##  Mean   :1.427   Mean   :1.133  
##  3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :2.000   Max.   :2.000</code></pre>
<p>Now, we are ready to run the RSM on the Liking for Science response data. We will use the <code>RSM()</code> function to run the model and store the results in an object called <code>RSM.science.</code></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="RS-model.html#cb9-1" aria-hidden="true" tabindex="-1"></a>RSM.science <span class="ot">&lt;-</span> <span class="fu">RSM</span>(science.responses, <span class="at">se =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><strong><em>Overall Model Summary</em></strong></p>
<p>Next, we will request a summary of the model results using the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="RS-model.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RSM.science)</span></code></pre></div>
<pre><code>## 
## Results of RSM estimation: 
## 
## Call:  RSM(X = science.responses, se = TRUE) 
## 
## Conditional log-likelihood: -1162.281 
## Number of iterations: 22 
## Number of parameters: 24 
## 
## Item (Category) Difficulty Parameters (eta): with 0.95 CI:
##       Estimate Std. Error lower CI upper CI
## i2      -0.748      0.210   -1.159   -0.337
## i3       0.319      0.184   -0.041    0.679
## i4       1.578      0.199    1.188    1.968
## i5       2.210      0.223    1.772    2.648
## i6       0.215      0.185   -0.147    0.577
## i7       0.966      0.186    0.601    1.330
## i8       1.502      0.197    1.116    1.888
## i9       0.591      0.183    0.232    0.950
## i10     -1.491      0.253   -1.986   -0.996
## i11     -0.983      0.221   -1.416   -0.551
## i13     -1.306      0.240   -1.776   -0.836
## i14      0.319      0.184   -0.041    0.679
## i15     -0.533      0.201   -0.927   -0.138
## i16      0.489      0.183    0.131    0.848
## i17      0.075      0.186   -0.291    0.440
## i18     -3.104      0.452   -3.990   -2.217
## i19     -2.455      0.349   -3.139   -1.771
## i20      1.656      0.201    1.261    2.050
## i21     -0.886      0.216   -1.309   -0.463
## i22      0.003      0.187   -0.364    0.371
## i23      1.984      0.213    1.566    2.402
## i24     -0.371      0.196   -0.756    0.013
## i25      0.421      0.183    0.062    0.780
## Cat 2    1.566      0.133    1.304    1.828
## 
## Item Easiness Parameters (beta) with 0.95 CI:
##             Estimate Std. Error lower CI upper CI
## beta i1.c1     0.451      0.199    0.062    0.840
## beta i1.c2    -0.664      0.409   -1.466    0.137
## beta i2.c1     0.748      0.210    0.337    1.159
## beta i2.c2    -0.071      0.426   -0.905    0.764
## beta i3.c1    -0.319      0.184   -0.679    0.041
## beta i3.c2    -2.203      0.396   -2.979   -1.428
## beta i4.c1    -1.578      0.199   -1.968   -1.188
## beta i4.c2    -4.722      0.447   -5.597   -3.847
## beta i5.c1    -2.210      0.223   -2.648   -1.772
## beta i5.c2    -5.986      0.499   -6.963   -5.009
## beta i6.c1    -0.215      0.185   -0.577    0.147
## beta i6.c2    -1.996      0.395   -2.771   -1.221
## beta i7.c1    -0.966      0.186   -1.330   -0.601
## beta i7.c2    -3.498      0.412   -4.306   -2.689
## beta i8.c1    -1.502      0.197   -1.888   -1.116
## beta i8.c2    -4.570      0.441   -5.436   -3.705
## beta i9.c1    -0.591      0.183   -0.950   -0.232
## beta i9.c2    -2.749      0.400   -3.533   -1.964
## beta i10.c1    1.491      0.253    0.996    1.986
## beta i10.c2    1.416      0.501    0.433    2.398
## beta i11.c1    0.983      0.221    0.551    1.416
## beta i11.c2    0.401      0.444   -0.470    1.271
## beta i13.c1    1.306      0.240    0.836    1.776
## beta i13.c2    1.046      0.478    0.110    1.982
## beta i14.c1   -0.319      0.184   -0.679    0.041
## beta i14.c2   -2.203      0.396   -2.979   -1.428
## beta i15.c1    0.533      0.201    0.138    0.927
## beta i15.c2   -0.501      0.413   -1.310    0.308
## beta i16.c1   -0.489      0.183   -0.848   -0.131
## beta i16.c2   -2.545      0.398   -3.325   -1.765
## beta i17.c1   -0.075      0.186   -0.440    0.291
## beta i17.c2   -1.715      0.396   -2.491   -0.940
## beta i18.c1    3.104      0.452    2.217    3.990
## beta i18.c2    4.641      0.896    2.885    6.397
## beta i19.c1    2.455      0.349    1.771    3.139
## beta i19.c2    3.344      0.690    1.992    4.695
## beta i20.c1   -1.656      0.201   -2.050   -1.261
## beta i20.c2   -4.877      0.452   -5.763   -3.991
## beta i21.c1    0.886      0.216    0.463    1.309
## beta i21.c2    0.206      0.436   -0.648    1.061
## beta i22.c1   -0.003      0.187   -0.371    0.364
## beta i22.c2   -1.573      0.396   -2.349   -0.796
## beta i23.c1   -1.984      0.213   -2.402   -1.566
## beta i23.c2   -5.535      0.478   -6.472   -4.598
## beta i24.c1    0.371      0.196   -0.013    0.756
## beta i24.c2   -0.824      0.406   -1.619   -0.029
## beta i25.c1   -0.421      0.183   -0.780   -0.062
## beta i25.c2   -2.409      0.397   -3.187   -1.631</code></pre>
<p>The summary of the RSM output includes the Conditional Log-likelihood statistic, details about the number of iterations and model parameters, and a table with item parameters, their standard errors, and confidence intervals. It is important to note that the item parameters included in this preliminary output are <em>item easiness</em> parameters–<em>not</em> item difficulty parameters. We will examine item difficulty parameters in detail later in our analysis.</p>
<p><strong><em>Wright Map</em></strong></p>
<p>Next, we will create a Wright Map (see Chapter 2) from our model results. This display will provide us with an overview of the distribution of person, item, and threshold parameters. We will create the plot using the <em>eRm</em> package function <code>plotPImap()</code> on the model object <code>RSM.science</code>.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="RS-model.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPImap</span>(RSM.science, <span class="at">main =</span> <span class="st">&quot;Liking for Science Rating Scale Model Wright Map&quot;</span>)</span></code></pre></div>
<p><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>In this <em>Wright Map</em> display, the results from the RSM analysis of the Liking for Science data are summarized graphically. The figure is organized as follows.</p>
<p>Starting at the bottom of the figure, the horizontal axis (labeled <em>Latent Dimension</em>) is the logit scale that represents the latent variable. In the application of the Liking for Science data, lower numbers indicate less-favorable attitudes toward science activities, and higher numbers indicate more-favorable attitudes toward science activities.</p>
<p>The central panel of the figure shows item difficulty locations on the logit scale for the 24 Liking for Science items that were included in the analysis; the y-axis for this panel shows the item labels. By default in <em>eRm</em>, the items are ordered according to their original order in the response matrix. The items can be ordered by difficulty by adding “sorted = TRUE” as an argument in the <code>plotPImap()</code> call. For each item, a solid circle plotting symbol shows the overall location estimate. This solid circle symbol is connected to two open-circle symbols that show the locations of the rating scale category thresholds. Each threshold is labeled with a “1” to indicate the threshold between rating scale category <em>x</em> = 0 and <em>x</em> = 1, or a “2” to indicate the threshold between rating scale category <em>x</em> = 1 and <em>x</em> = 2.</p>
<p>The upper panel of the figure shows a histogram of person (in this case, children) location estimates on the logit scale. Small vertical lines on the x-axis of this histogram show the points on the logit scale at which information (variance) is maximized for the sample of persons and items in the analysis. These lines can be omitted by adding <code>irug = FALSE</code> as an argument in the <code>plotPImap()</code> call.</p>
<p><strong><em>Item Parameters</em></strong></p>
<p>Next, we will examine the item difficulty location and rating scale category threshold estimates. The <em>eRm</em> package provides several options with which analysts can find and examine item and rating scale category threshold parameters. For example, one way to obtain the overall item location parameters (<span class="math inline">\(\delta\)</span>) is to extract the <em>eta parameters</em> from the model object using the $ operator. We extract these parameters, print them to the console, and calculate summary statistics for them with the following code.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="RS-model.html#cb13-1" aria-hidden="true" tabindex="-1"></a>item.locations <span class="ot">&lt;-</span> RSM.science<span class="sc">$</span>etapar</span>
<span id="cb13-2"><a href="RS-model.html#cb13-2" aria-hidden="true" tabindex="-1"></a>item.locations</span></code></pre></div>
<pre><code>##           i2           i3           i4           i5           i6           i7 
## -0.747716237  0.318637705  1.578076249  2.209910144  0.214960484  0.965680071 
##           i8           i9          i10          i11          i13          i14 
##  1.502096325  0.591198710 -1.490900062 -0.983450547 -1.306083786  0.318637700 
##          i15          i16          i17          i18          i19          i20 
## -0.532510932  0.489411243  0.074568234 -3.103553567 -2.454966823  1.655551546 
##          i21          i22          i23          i24          i25        Cat 2 
## -0.886223768  0.003185124  1.984230774 -0.371230973  0.421330341  1.566148493</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="RS-model.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(item.locations)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -3.10355 -0.78234  0.26680  0.08404  1.09978  2.20991</code></pre>
<p>Because of the nature of the estimation process used in <em>eRm</em>, the <code>item.locations</code> object that we just created does not include the location estimate for the first item. One can calculate the location for item 1 by subtracting the sum of the item locations from zero. In the following code, we find the location for item 1, and then create a new object with all 24 item locations.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="RS-model.html#cb17-1" aria-hidden="true" tabindex="-1"></a>n.items <span class="ot">&lt;-</span> <span class="fu">ncol</span>(science.responses)</span>
<span id="cb17-2"><a href="RS-model.html#cb17-2" aria-hidden="true" tabindex="-1"></a>i1 <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">-</span> <span class="fu">sum</span>(item.locations[<span class="dv">1</span><span class="sc">:</span>(n.items <span class="sc">-</span> <span class="dv">1</span>)])</span>
<span id="cb17-3"><a href="RS-model.html#cb17-3" aria-hidden="true" tabindex="-1"></a>item.locations.all <span class="ot">&lt;-</span> <span class="fu">c</span>(i1, item.locations[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>(n.items <span class="sc">-</span> <span class="dv">1</span>))])</span>
<span id="cb17-4"><a href="RS-model.html#cb17-4" aria-hidden="true" tabindex="-1"></a>item.locations.all</span></code></pre></div>
<pre><code>##                        i2           i3           i4           i5           i6 
## -0.450837954 -0.747716237  0.318637705  1.578076249  2.209910144  0.214960484 
##           i7           i8           i9          i10          i11          i13 
##  0.965680071  1.502096325  0.591198710 -1.490900062 -0.983450547 -1.306083786 
##          i14          i15          i16          i17          i18          i19 
##  0.318637700 -0.532510932  0.489411243  0.074568234 -3.103553567 -2.454966823 
##          i20          i21          i22          i23          i24          i25 
##  1.655551546 -0.886223768  0.003185124  1.984230774 -0.371230973  0.421330341</code></pre>
<p>Alternatively, one can apply the <code>thresholds()</code> function to the model object in order to find the item locations from the RSM. This procedure provides item location estimates (<span class="math inline">\(\delta\) as well as estimates of the item location combined with rating scale category thresholds (\)</span> + $). However, the values produced with this function are not centered at zero logits, so a little manipulation is required to obtain the centered values. In the following code chunk, we apply the <code>thresholds()</code> function to obtain the uncentered item location estimates and then calculate centered item locations.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="RS-model.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply thresholds() function to the model object in order to obtain item locations (not centered at zero logits):</span></span>
<span id="cb19-2"><a href="RS-model.html#cb19-2" aria-hidden="true" tabindex="-1"></a>items.and.taus <span class="ot">&lt;-</span> <span class="fu">thresholds</span>(RSM.science)</span>
<span id="cb19-3"><a href="RS-model.html#cb19-3" aria-hidden="true" tabindex="-1"></a>items.and.taus.table <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(items.and.taus<span class="sc">$</span>threshtable)</span>
<span id="cb19-4"><a href="RS-model.html#cb19-4" aria-hidden="true" tabindex="-1"></a>uncentered.item.locations <span class="ot">&lt;-</span> items.and.taus.table<span class="sc">$</span>X1.Location</span>
<span id="cb19-5"><a href="RS-model.html#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="RS-model.html#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the mean of the item locations to zero logits:</span></span>
<span id="cb19-7"><a href="RS-model.html#cb19-7" aria-hidden="true" tabindex="-1"></a>centered.item.locations <span class="ot">&lt;-</span> <span class="fu">scale</span>(uncentered.item.locations, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-8"><a href="RS-model.html#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(centered.item.locations)</span></code></pre></div>
<pre><code>##        V1         
##  Min.   :-3.1036  
##  1st Qu.:-0.7823  
##  Median : 0.1448  
##  Mean   : 0.0000  
##  3rd Qu.: 0.6848  
##  Max.   : 2.2099</code></pre>
<p>In addition, the eta parameters from the RSM object include <em>cumulative</em> rating scale category thresholds, printed after the final item location estimate. In our example, this value is labeled “Cat 2.” Cumulative thresholds are not typically used in Rasch model applications; Rasch-Andrich (i.e., adjacent categories) thresholds are typically used instead <span class="citation">(<a href="#ref-Prob_PM" role="doc-biblioref">Andrich 2015</a>; <a href="#ref-Conceptual_notes" role="doc-biblioref">Mellenbergh 1995</a>)</span>. We will calculate the values of the rating scale category thresholds using the results from the <code>thresholds()</code> function. This function produced estimates of the rating scale category thresholds combined with item difficulty parameter estimates. We can subtract these values from the item locations to find the values of each threshold.</p>
<p>In our example, we have a rating scale with three categories, so we have two rating scale category thresholds. In the following code chunk, we create an empty object in which to store the threshold estimates (<code>tau.estimates</code>), and then we use a for-loop to calculate the estimates and store them in our object. Because the thresholds are the same for all of the items, we will save the first value from vector of differences between the item+threshold locations and the overall locations.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="RS-model.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the number of thresholds as the maximum observed score in the response matrix (be sure the responses begin at category 0):</span></span>
<span id="cb21-2"><a href="RS-model.html#cb21-2" aria-hidden="true" tabindex="-1"></a>n.thresholds <span class="ot">&lt;-</span> <span class="fu">max</span>(science.responses)</span>
<span id="cb21-3"><a href="RS-model.html#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="RS-model.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate adjacent-category threshold values:</span></span>
<span id="cb21-5"><a href="RS-model.html#cb21-5" aria-hidden="true" tabindex="-1"></a>tau.estimates <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb21-6"><a href="RS-model.html#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="RS-model.html#cb21-7" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb21-8"><a href="RS-model.html#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(tau <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n.thresholds){</span>
<span id="cb21-9"><a href="RS-model.html#cb21-9" aria-hidden="true" tabindex="-1"></a>  tau.estimates[tau] <span class="ot">&lt;-</span> (items.and.taus.table[, (<span class="dv">1</span><span class="sc">+</span>tau)] <span class="sc">-</span> items.and.taus.table[,<span class="dv">1</span>])[<span class="dv">1</span>]</span>
<span id="cb21-10"><a href="RS-model.html#cb21-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Next, we will calculate standard errors for each item and threshold location and store them in new objects. We will use <code>summary()</code> to examine descriptive statistics for these values.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="RS-model.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SE for items + thresholds:</span></span>
<span id="cb22-2"><a href="RS-model.html#cb22-2" aria-hidden="true" tabindex="-1"></a>delta.tau.se <span class="ot">&lt;-</span> items.and.taus<span class="sc">$</span>se.thresh</span>
<span id="cb22-3"><a href="RS-model.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(delta.tau.se)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.1831  0.1989  0.2303  0.2379  0.2459  0.4535</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="RS-model.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SE for overall item:</span></span>
<span id="cb24-2"><a href="RS-model.html#cb24-2" aria-hidden="true" tabindex="-1"></a>delta.se <span class="ot">&lt;-</span> RSM.science<span class="sc">$</span>se.eta</span>
<span id="cb24-3"><a href="RS-model.html#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(delta.se)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.1335  0.1844  0.1980  0.2153  0.2172  0.4524</code></pre>
<p><strong><em>Item Response Functions</em></strong></p>
<p>We will examine graphical displays of item difficulty using item response functions. With the RSM, the <em>eRm</em> package creates plots of the probability for a rating in each rating scale category, conditional on person locations on the latent variable. In the following code, we use <code>plotICC()</code> from <em>eRm</em> to create rating scale category probability plots for the 24 items in our analysis. We included <code>ask = FALSE</code> in our function call in order to generate all of the plots at once. For brevity, we have only included plots for the first three items in this book. The specific items to be plotted can be controlled by changing the items included in the <code>items.to.plot</code> object.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="RS-model.html#cb26-1" aria-hidden="true" tabindex="-1"></a>items.to.plot <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb26-2"><a href="RS-model.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotICC</span>(RSM.science, <span class="at">ask =</span> <span class="cn">FALSE</span>, <span class="at">item.subset =</span> items.to.plot)</span></code></pre></div>
<p><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-16-1.png" width="672" /><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-16-2.png" width="672" /><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-16-3.png" width="672" /></p>
<p>This code generates plots of rating scale category probabilities for each item. In each item-specific plot, the x-axis is the logit scale that represents the latent variable; this scale represents favorability toward science activities in our example. The y-axis is the probability for a rating in each category, conditional on person locations on the latent variable. Separate lines in different colors show the conditional probability for each category of responses observed for the item of interest. Because we used the RSM, the overall shape of the curves and the relative distance between the curves is consistent across items–reflecting the common set of rating scale category thresholds. However, the location of the curves on the logit scale shifts across the individual items–reflecting each item’s unique overall difficulty location (<span class="math inline">\(\delta\)</span>).</p>
<p><strong><em>Person Parameters and Item Fit</em></strong></p>
<p>In the <em>eRm</em> package, it is necessary to calculate person parameters <em>before</em> item fit statistics can be calculated. Accordingly, we will proceed with a brief examination of person parameters before we conduct item fit analyses. In practice, we recommend examining item fit before examining and interpreting item locations in detail.</p>
<p><strong><em>Examine Person Parameters</em></strong></p>
<p>The next step in our analysis is to calculate and examine person location parameters (i.e., person achievement or ability estimates). With the CMLE method that is used in <em>eRm</em>, person parameters are calculated <em>after</em> the item locations are estimated.</p>
<p>In the following code, we calculate person locations that correspond to our model using the <code>person.parameter()</code> function with the RSM model object (<code>RSM.science</code>). This function also produces standard errors for the person locations. We stored the person location estimates and their standard errors in a new data frame called <code>person.locations</code>, and then requested a summary of the estimation results using <code>summary()</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="RS-model.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate person parameters:</span></span>
<span id="cb27-2"><a href="RS-model.html#cb27-2" aria-hidden="true" tabindex="-1"></a>person.locations.estimate <span class="ot">&lt;-</span> <span class="fu">person.parameter</span>(RSM.science)</span>
<span id="cb27-3"><a href="RS-model.html#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="RS-model.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Store person parameters and their standard errors in a dataframe object:</span></span>
<span id="cb27-5"><a href="RS-model.html#cb27-5" aria-hidden="true" tabindex="-1"></a>person.locations <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(person.locations.estimate<span class="sc">$</span>thetapar,</span>
<span id="cb27-6"><a href="RS-model.html#cb27-6" aria-hidden="true" tabindex="-1"></a>                                     person.locations.estimate<span class="sc">$</span>se.theta)</span>
<span id="cb27-7"><a href="RS-model.html#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(person.locations) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;theta&quot;</span>, <span class="st">&quot;SE&quot;</span>)</span>
<span id="cb27-8"><a href="RS-model.html#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="RS-model.html#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary statistics for person parameters:</span></span>
<span id="cb27-10"><a href="RS-model.html#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(person.locations)</span></code></pre></div>
<pre><code>##      theta               SE        
##  Min.   :-0.8248   Min.   :0.3362  
##  1st Qu.: 0.8173   1st Qu.:0.3377  
##  Median : 1.3296   Median :0.3474  
##  Mean   : 1.5669   Mean   :0.3819  
##  3rd Qu.: 2.2379   3rd Qu.:0.3768  
##  Max.   : 5.3886   Max.   :1.0285</code></pre>
<p>The estimation procedure in <em>eRm</em> does not directly produce parameter estimates for persons with extreme scores. In our example, extreme scores would result from a child giving a response of <em>x</em> = 0 to all items or a child giving a response of <em>x</em> = 2 to all items. For these students, a standard error is not calculated. In our example, Child #2 had an extreme score because they gave a rating in category 2 to all items.</p>
<p><strong><em>Examine Item Fit</em></strong></p>
<p>Next, we will conduct a brief exploration of item fit statistics for the Liking for Science items. We considered item fit in detail in Chapter 3; readers can use the same procedures in that chapter to examine item fit in detail for the RSM.</p>
<p>To calculate numeric item fit statistics, we will use the function <code>itemfit()</code> from eRm on the person parameter object (<code>person.locations.estimate</code>). This function produces several item fit statistics, including infit mean square error (MSE), outfit MSE, and standardized infit and outfit MSE statistics. We will store the item fit results in a new object called <code>item.fit</code>, and then format this object as a data.frame object for easy manipulation and exporting.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="RS-model.html#cb29-1" aria-hidden="true" tabindex="-1"></a>item.fit.results <span class="ot">&lt;-</span> <span class="fu">itemfit</span>(person.locations.estimate)</span>
<span id="cb29-2"><a href="RS-model.html#cb29-2" aria-hidden="true" tabindex="-1"></a>item.fit <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(item.fit.results<span class="sc">$</span>i.infitMSQ,</span>
<span id="cb29-3"><a href="RS-model.html#cb29-3" aria-hidden="true" tabindex="-1"></a>                             item.fit.results<span class="sc">$</span>i.outfitMSQ,</span>
<span id="cb29-4"><a href="RS-model.html#cb29-4" aria-hidden="true" tabindex="-1"></a>                             item.fit.results<span class="sc">$</span>i.infitZ,</span>
<span id="cb29-5"><a href="RS-model.html#cb29-5" aria-hidden="true" tabindex="-1"></a>                             item.fit.results<span class="sc">$</span>i.outfitZ)</span>
<span id="cb29-6"><a href="RS-model.html#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(item.fit) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;infit_MSE&quot;</span>, <span class="st">&quot;outfit_MSE&quot;</span>, <span class="st">&quot;std_infit&quot;</span>, <span class="st">&quot;std_outfit&quot;</span>)</span></code></pre></div>
<p>Next, we will request a summary of the numeric item fit statistics using <code>summary()</code>.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="RS-model.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(item.fit)</span></code></pre></div>
<pre><code>##    infit_MSE        outfit_MSE       std_infit         std_outfit     
##  Min.   :0.5296   Min.   :0.4734   Min.   :-3.8138   Min.   :-3.2246  
##  1st Qu.:0.7671   1st Qu.:0.6360   1st Qu.:-1.6470   1st Qu.:-1.6652  
##  Median :0.8614   Median :0.7457   Median :-0.9102   Median :-1.0783  
##  Mean   :0.9968   Mean   :1.0492   Mean   :-0.4152   Mean   :-0.1794  
##  3rd Qu.:1.0764   3rd Qu.:1.0533   3rd Qu.: 0.5623   3rd Qu.: 0.3292  
##  Max.   :2.3164   Max.   :3.7723   Max.   : 5.9898   Max.   : 8.4184</code></pre>
<p>The <code>item.fit</code> object includes mean square error (<em>MSE</em>) and standardized (<em>Z</em>) versions of the Outfit and Infit statistics for each item included in the analysis.These statistics are summaries of the residuals associated with each item. When data fit Rasch model expectations, the MSE versions of Outfit and Infit are expected to be close to 1.00 and the standardized versions of Outfit and Infit are expected to be around 0.00. Please refer to Chapter 3 for a more-detailed discussion of item fit.</p>
<p>Then, we calculate the reliability of separation statistics using the similar code we mentioned in the Chapter 3.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="RS-model.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Person separation reliability</span></span>
<span id="cb32-2"><a href="RS-model.html#cb32-2" aria-hidden="true" tabindex="-1"></a>person.separation.reliability <span class="ot">&lt;-</span> <span class="fu">SepRel</span>(person.locations.estimate)</span>
<span id="cb32-3"><a href="RS-model.html#cb32-3" aria-hidden="true" tabindex="-1"></a>person.separation.reliability</span></code></pre></div>
<pre><code>## Separation Reliability: 0.8874</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="RS-model.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Item separation reliability:</span></span>
<span id="cb34-2"><a href="RS-model.html#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="RS-model.html#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get Item scores</span></span>
<span id="cb34-4"><a href="RS-model.html#cb34-4" aria-hidden="true" tabindex="-1"></a>ItemScores <span class="ot">&lt;-</span> <span class="fu">colSums</span>(science.responses)</span>
<span id="cb34-5"><a href="RS-model.html#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="RS-model.html#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get Item SD</span></span>
<span id="cb34-7"><a href="RS-model.html#cb34-7" aria-hidden="true" tabindex="-1"></a>ItemSD <span class="ot">&lt;-</span> <span class="fu">apply</span>(science.responses,<span class="dv">2</span>,sd)</span>
<span id="cb34-8"><a href="RS-model.html#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="RS-model.html#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the se of the Item</span></span>
<span id="cb34-10"><a href="RS-model.html#cb34-10" aria-hidden="true" tabindex="-1"></a>ItemSE <span class="ot">&lt;-</span> ItemSD<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(ItemSD))</span>
<span id="cb34-11"><a href="RS-model.html#cb34-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="RS-model.html#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the Observed Variance (also known as Total Person Variability or Squared Standard Deviation)</span></span>
<span id="cb34-13"><a href="RS-model.html#cb34-13" aria-hidden="true" tabindex="-1"></a>SSD.ItemScores <span class="ot">&lt;-</span> <span class="fu">var</span>(ItemScores)</span>
<span id="cb34-14"><a href="RS-model.html#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="RS-model.html#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the Mean Square Measurement error (also known as Model Error variance)</span></span>
<span id="cb34-16"><a href="RS-model.html#cb34-16" aria-hidden="true" tabindex="-1"></a>Item.MSE <span class="ot">&lt;-</span> <span class="fu">sum</span>((ItemSE)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">length</span>(ItemSE)</span>
<span id="cb34-17"><a href="RS-model.html#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="RS-model.html#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the Item Separation Reliability</span></span>
<span id="cb34-19"><a href="RS-model.html#cb34-19" aria-hidden="true" tabindex="-1"></a>item.separation.reliability <span class="ot">&lt;-</span> (SSD.ItemScores<span class="sc">-</span>Item.MSE) <span class="sc">/</span> SSD.ItemScores</span>
<span id="cb34-20"><a href="RS-model.html#cb34-20" aria-hidden="true" tabindex="-1"></a>item.separation.reliability</span></code></pre></div>
<pre><code>## [1] 0.9999806</code></pre>
<p><strong><em>Person Fit</em></strong></p>
<p>Next, we will conduct a brief exploration of person fit statistics. To calculate numeric person fit statistics, we will use the function <code>personfit()</code> from <em>eRm</em> on the person parameter object (<code>person.locations.estimate</code>). This function produces several person fit statistics, including infit mean square error (MSE), outfit MSE, and standardized infit and outfit MSE statistics. We will store the person fit results in a new object called <code>person.fit</code>, and then format this object as a dataframe for easier manipulation and exporting.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="RS-model.html#cb36-1" aria-hidden="true" tabindex="-1"></a>person.fit.results <span class="ot">&lt;-</span> <span class="fu">personfit</span>(person.locations.estimate)</span>
<span id="cb36-2"><a href="RS-model.html#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="RS-model.html#cb36-3" aria-hidden="true" tabindex="-1"></a>person.fit <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(person.fit.results<span class="sc">$</span>p.infitMSQ,</span>
<span id="cb36-4"><a href="RS-model.html#cb36-4" aria-hidden="true" tabindex="-1"></a>                             person.fit.results<span class="sc">$</span>p.outfitMSQ,</span>
<span id="cb36-5"><a href="RS-model.html#cb36-5" aria-hidden="true" tabindex="-1"></a>                             person.fit.results<span class="sc">$</span>p.infitZ,</span>
<span id="cb36-6"><a href="RS-model.html#cb36-6" aria-hidden="true" tabindex="-1"></a>                             person.fit.results<span class="sc">$</span>p.outfitZ)</span>
<span id="cb36-7"><a href="RS-model.html#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(person.fit) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;infit_MSE&quot;</span>, <span class="st">&quot;outfit_MSE&quot;</span>, <span class="st">&quot;std_infit&quot;</span>, <span class="st">&quot;std_outfit&quot;</span>)</span></code></pre></div>
<p>Next, we will request a summary of the numeric person fit statistics using the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="RS-model.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(person.fit)</span></code></pre></div>
<pre><code>##    infit_MSE        outfit_MSE       std_infit         std_outfit     
##  Min.   :0.2754   Min.   :0.2179   Min.   :-4.0391   Min.   :-3.1064  
##  1st Qu.:0.6635   1st Qu.:0.5470   1st Qu.:-1.2749   1st Qu.:-1.0372  
##  Median :0.8496   Median :0.7221   Median :-0.3387   Median :-0.4563  
##  Mean   :0.9588   Mean   :1.0492   Mean   :-0.2829   Mean   : 0.0243  
##  3rd Qu.:1.0851   3rd Qu.:1.1367   3rd Qu.: 0.3712   3rd Qu.: 0.5296  
##  Max.   :3.0474   Max.   :4.8182   Max.   : 5.1958   Max.   : 6.6751</code></pre>
<p>The <em>person.fit</em> object includes mean square error (<em>MSE</em>) and standardized (<em>Z</em>) versions of the Outfit and Infit statistics for each person. These statistics are summaries of the residuals associated with each person. When data fit Rasch model expectations, the MSE versions of Outfit and Infit are expected to be close to 1.00 and the standardized versions of Outfit and Infit are expected to be around 0.00. Please refer to Chapter 3 for a more-detailed discussion of person fit.</p>
<p><strong><em>Summarize the Results in Tables</em></strong></p>
<p>As a final step, we will create tables that summarize the calibrations of the persons, items, and rating scale category thresholds.</p>
<p>Table 1 is an overall model summary table that provides an overview of the logit scale locations, standard errors, fit statistics, and reliability statistics for items and persons. This type of table is useful for reporting the results from Rasch model analyses because it provides a quick overview of the location estimates and numeric model-data fit statistics for the items and persons in the analysis.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="RS-model.html#cb39-1" aria-hidden="true" tabindex="-1"></a>RSM_summary.table.statistics <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Logit Scale Location Mean&quot;</span>,</span>
<span id="cb39-2"><a href="RS-model.html#cb39-2" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Logit Scale Location SD&quot;</span>,</span>
<span id="cb39-3"><a href="RS-model.html#cb39-3" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Standard Error Mean&quot;</span>,</span>
<span id="cb39-4"><a href="RS-model.html#cb39-4" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Standard Error SD&quot;</span>,</span>
<span id="cb39-5"><a href="RS-model.html#cb39-5" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Outfit MSE Mean&quot;</span>,</span>
<span id="cb39-6"><a href="RS-model.html#cb39-6" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Outfit MSE SD&quot;</span>,</span>
<span id="cb39-7"><a href="RS-model.html#cb39-7" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Infit MSE Mean&quot;</span>,</span>
<span id="cb39-8"><a href="RS-model.html#cb39-8" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Infit MSE SD&quot;</span>,</span>
<span id="cb39-9"><a href="RS-model.html#cb39-9" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Std. Outfit Mean&quot;</span>,</span>
<span id="cb39-10"><a href="RS-model.html#cb39-10" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Std. Outfit SD&quot;</span>,</span>
<span id="cb39-11"><a href="RS-model.html#cb39-11" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Std. Infit Mean&quot;</span>,</span>
<span id="cb39-12"><a href="RS-model.html#cb39-12" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Std. Infit SD&quot;</span>,</span>
<span id="cb39-13"><a href="RS-model.html#cb39-13" aria-hidden="true" tabindex="-1"></a>                              <span class="st">&quot;Separation.reliability&quot;</span>)</span>
<span id="cb39-14"><a href="RS-model.html#cb39-14" aria-hidden="true" tabindex="-1"></a>                              </span>
<span id="cb39-15"><a href="RS-model.html#cb39-15" aria-hidden="true" tabindex="-1"></a>RSM_item.summary.results <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">mean</span>(centered.item.locations),</span>
<span id="cb39-16"><a href="RS-model.html#cb39-16" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(centered.item.locations),</span>
<span id="cb39-17"><a href="RS-model.html#cb39-17" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(delta.se),</span>
<span id="cb39-18"><a href="RS-model.html#cb39-18" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(delta.se),</span>
<span id="cb39-19"><a href="RS-model.html#cb39-19" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(item.fit.results<span class="sc">$</span>i.outfitMSQ),</span>
<span id="cb39-20"><a href="RS-model.html#cb39-20" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(item.fit.results<span class="sc">$</span>i.outfitMSQ),</span>
<span id="cb39-21"><a href="RS-model.html#cb39-21" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(item.fit.results<span class="sc">$</span>i.infitMSQ),</span>
<span id="cb39-22"><a href="RS-model.html#cb39-22" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(item.fit.results<span class="sc">$</span>i.infitMSQ),</span>
<span id="cb39-23"><a href="RS-model.html#cb39-23" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(item.fit.results<span class="sc">$</span>i.outfitZ),</span>
<span id="cb39-24"><a href="RS-model.html#cb39-24" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(item.fit.results<span class="sc">$</span>i.outfitZ),</span>
<span id="cb39-25"><a href="RS-model.html#cb39-25" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(item.fit.results<span class="sc">$</span>i.infitZ),</span>
<span id="cb39-26"><a href="RS-model.html#cb39-26" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(item.fit.results<span class="sc">$</span>i.infitZ),</span>
<span id="cb39-27"><a href="RS-model.html#cb39-27" aria-hidden="true" tabindex="-1"></a>                              item.separation.reliability)</span>
<span id="cb39-28"><a href="RS-model.html#cb39-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-29"><a href="RS-model.html#cb39-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-30"><a href="RS-model.html#cb39-30" aria-hidden="true" tabindex="-1"></a>RSM_person.summary.results <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">mean</span>(person.locations<span class="sc">$</span>theta),</span>
<span id="cb39-31"><a href="RS-model.html#cb39-31" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(person.locations<span class="sc">$</span>theta),</span>
<span id="cb39-32"><a href="RS-model.html#cb39-32" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(person.locations<span class="sc">$</span>SE),</span>
<span id="cb39-33"><a href="RS-model.html#cb39-33" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(person.locations<span class="sc">$</span>SE),</span>
<span id="cb39-34"><a href="RS-model.html#cb39-34" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(person.fit<span class="sc">$</span>outfit_MSE),</span>
<span id="cb39-35"><a href="RS-model.html#cb39-35" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(person.fit<span class="sc">$</span>outfit_MSE),</span>
<span id="cb39-36"><a href="RS-model.html#cb39-36" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(person.fit<span class="sc">$</span>infit_MSE),</span>
<span id="cb39-37"><a href="RS-model.html#cb39-37" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(person.fit<span class="sc">$</span>infit_MSE),</span>
<span id="cb39-38"><a href="RS-model.html#cb39-38" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(person.fit<span class="sc">$</span>std_outfit),</span>
<span id="cb39-39"><a href="RS-model.html#cb39-39" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(person.fit<span class="sc">$</span>std_outfit),</span>
<span id="cb39-40"><a href="RS-model.html#cb39-40" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">mean</span>(person.fit<span class="sc">$</span>std_infit),</span>
<span id="cb39-41"><a href="RS-model.html#cb39-41" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">sd</span>(person.fit<span class="sc">$</span>std_infit),</span>
<span id="cb39-42"><a href="RS-model.html#cb39-42" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">as.numeric</span>(person.separation.reliability))</span>
<span id="cb39-43"><a href="RS-model.html#cb39-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-44"><a href="RS-model.html#cb39-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Round the values for presentation in a table:</span></span>
<span id="cb39-45"><a href="RS-model.html#cb39-45" aria-hidden="true" tabindex="-1"></a>RSM_item.summary.results_rounded <span class="ot">&lt;-</span> <span class="fu">round</span>(RSM_item.summary.results, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb39-46"><a href="RS-model.html#cb39-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-47"><a href="RS-model.html#cb39-47" aria-hidden="true" tabindex="-1"></a>RSM_person.summary.results_rounded <span class="ot">&lt;-</span> <span class="fu">round</span>(RSM_person.summary.results, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb39-48"><a href="RS-model.html#cb39-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-49"><a href="RS-model.html#cb39-49" aria-hidden="true" tabindex="-1"></a>RSM_Table1 <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(RSM_summary.table.statistics,</span>
<span id="cb39-50"><a href="RS-model.html#cb39-50" aria-hidden="true" tabindex="-1"></a>                           RSM_item.summary.results_rounded, </span>
<span id="cb39-51"><a href="RS-model.html#cb39-51" aria-hidden="true" tabindex="-1"></a>                           RSM_person.summary.results_rounded)</span>
<span id="cb39-52"><a href="RS-model.html#cb39-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-53"><a href="RS-model.html#cb39-53" aria-hidden="true" tabindex="-1"></a><span class="co"># add descriptive column labels:</span></span>
<span id="cb39-54"><a href="RS-model.html#cb39-54" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(RSM_Table1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Statistic&quot;</span>, <span class="st">&quot;Items&quot;</span>, <span class="st">&quot;Persons&quot;</span>)  </span>
<span id="cb39-55"><a href="RS-model.html#cb39-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-56"><a href="RS-model.html#cb39-56" aria-hidden="true" tabindex="-1"></a>RSM_Table1</span></code></pre></div>
<pre><code>##                                             Statistic Items Persons    NA    NA
## X                           Logit Scale Location Mean  0.00    1.57  1.57  1.57
## X.1                           Logit Scale Location SD  1.33    1.18  1.18  1.18
## X.2                               Standard Error Mean  0.22    0.38  0.38  0.38
## X.3                                 Standard Error SD  0.06    0.10  0.10  0.10
## X.4                                   Outfit MSE Mean  1.05    1.05  1.05  1.05
## X.5                                     Outfit MSE SD  0.82    0.99  0.99  0.99
## X.6                                    Infit MSE Mean  1.00    0.96  0.96  0.96
## X.7                                      Infit MSE SD  0.45    0.49  0.49  0.49
## X.8                                  Std. Outfit Mean -0.18    0.02  0.02  0.02
## X.9                                    Std. Outfit SD  2.77    1.85  1.85  1.85
## X.10                                  Std. Infit Mean -0.42   -0.28 -0.28 -0.28
## X.11                                    Std. Infit SD  2.35    1.63  1.63  1.63
## item.separation.reliability    Separation.reliability  1.00    0.89  1.39  0.16</code></pre>
<p>Table 2 is a table that summarizes the overall calibrations of individual items. For data sets with manageable sample sizes such as the Liking for Science data example in this chapter, we recommend reporting details about each item in a table similar to this one.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="RS-model.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average rating for each item:</span></span>
<span id="cb41-2"><a href="RS-model.html#cb41-2" aria-hidden="true" tabindex="-1"></a>Avg_Rating <span class="ot">&lt;-</span> <span class="fu">apply</span>(science.responses, <span class="dv">2</span>, mean)</span>
<span id="cb41-3"><a href="RS-model.html#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="RS-model.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine item calibration results in a table:</span></span>
<span id="cb41-5"><a href="RS-model.html#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="RS-model.html#cb41-6" aria-hidden="true" tabindex="-1"></a>RSM_Table2 <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(science.responses)), </span>
<span id="cb41-7"><a href="RS-model.html#cb41-7" aria-hidden="true" tabindex="-1"></a>                           Avg_Rating,</span>
<span id="cb41-8"><a href="RS-model.html#cb41-8" aria-hidden="true" tabindex="-1"></a>                           centered.item.locations,</span>
<span id="cb41-9"><a href="RS-model.html#cb41-9" aria-hidden="true" tabindex="-1"></a>                           delta.se,</span>
<span id="cb41-10"><a href="RS-model.html#cb41-10" aria-hidden="true" tabindex="-1"></a>                           item.fit<span class="sc">$</span>outfit_MSE,</span>
<span id="cb41-11"><a href="RS-model.html#cb41-11" aria-hidden="true" tabindex="-1"></a>                           item.fit<span class="sc">$</span>std_outfit,</span>
<span id="cb41-12"><a href="RS-model.html#cb41-12" aria-hidden="true" tabindex="-1"></a>                           item.fit<span class="sc">$</span>infit_MSE,</span>
<span id="cb41-13"><a href="RS-model.html#cb41-13" aria-hidden="true" tabindex="-1"></a>                           item.fit<span class="sc">$</span>std_infit)</span>
<span id="cb41-14"><a href="RS-model.html#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(RSM_Table2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Task ID&quot;</span>, <span class="st">&quot;Average Rating&quot;</span>, <span class="st">&quot;Item Location&quot;</span>,<span class="st">&quot;Item SE&quot;</span>,<span class="st">&quot;Outfit MSE&quot;</span>,<span class="st">&quot;Std. Outfit&quot;</span>, <span class="st">&quot;Infit MSE&quot;</span>,<span class="st">&quot;Std. Infit&quot;</span>)                           </span>
<span id="cb41-15"><a href="RS-model.html#cb41-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-16"><a href="RS-model.html#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort Table 2 by Item difficulty:</span></span>
<span id="cb41-17"><a href="RS-model.html#cb41-17" aria-hidden="true" tabindex="-1"></a>RSM_Table2 <span class="ot">&lt;-</span> RSM_Table2[<span class="fu">order</span>(<span class="sc">-</span>RSM_Table2<span class="sc">$</span><span class="st">`</span><span class="at">Item Location</span><span class="st">`</span>),]</span>
<span id="cb41-18"><a href="RS-model.html#cb41-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-19"><a href="RS-model.html#cb41-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Round the numeric values (all columns except the first one) to 2 digits:</span></span>
<span id="cb41-20"><a href="RS-model.html#cb41-20" aria-hidden="true" tabindex="-1"></a>RSM_Table2[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(RSM_Table2[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb41-21"><a href="RS-model.html#cb41-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-22"><a href="RS-model.html#cb41-22" aria-hidden="true" tabindex="-1"></a>RSM_Table2</span></code></pre></div>
<pre><code>##     Task ID Average Rating Item Location Item SE Outfit MSE Std. Outfit
## i5        5           0.49          2.21    0.18       3.29        6.77
## i23      22           0.56          1.98    0.20       3.77        8.42
## i20      19           0.67          1.66    0.22       1.67        3.16
## i4        4           0.69          1.58    0.22       0.86       -0.78
## i8        8           0.72          1.50    0.18       1.15        0.87
## i7        7           0.92          0.97    0.20       0.97       -0.15
## i9        9           1.07          0.59    0.25       1.13        0.81
## i16      15           1.11          0.49    0.19       0.90       -0.53
## i25      24           1.13          0.42    0.13       0.71       -1.83
## i3        3           1.17          0.32    0.20       0.52       -3.22
## i14      13           1.17          0.32    0.20       0.72       -1.65
## i6        6           1.21          0.21    0.19       0.72       -1.60
## i17      16           1.27          0.07    0.45       0.57       -2.56
## i22      21           1.29          0.00    0.21       0.72       -1.50
## i24      23           1.43         -0.37    0.18       0.77       -1.04
## i1        1           1.45         -0.45    0.21       0.48       -2.68
## i15      14           1.48         -0.53    0.18       0.62       -1.71
## i2        2           1.55         -0.75    0.18       0.71       -1.12
## i21      20           1.59         -0.89    0.19       0.64       -1.35
## i11      11           1.61         -0.98    0.24       0.47       -2.10
## i13      12           1.69         -1.31    0.18       0.93       -0.09
## i10      10           1.73         -1.49    0.22       0.56       -1.23
## i19      18           1.88         -2.45    0.20       1.03        0.25
## i18      17           1.93         -3.10    0.35       1.26        0.56
##     Infit MSE Std. Infit
## i5       2.20       5.31
## i23      2.32       5.99
## i20      1.27       1.66
## i4       0.85      -0.99
## i8       1.06       0.42
## i7       0.94      -0.42
## i9       1.14       0.99
## i16      0.92      -0.53
## i25      0.76      -1.82
## i3       0.55      -3.81
## i14      0.79      -1.58
## i6       0.78      -1.67
## i17      0.63      -2.92
## i22      0.80      -1.41
## i24      0.87      -0.83
## i1       0.53      -3.65
## i15      0.76      -1.64
## i2       0.90      -0.55
## i21      0.82      -1.03
## i11      0.60      -2.64
## i13      1.20       1.02
## i10      0.77      -1.14
## i19      1.04       0.23
## i18      1.43       1.05</code></pre>
<p>Finally, Table 3 provides a summary of the person calibrations. When there is a relatively large person sample size, it may be more useful to present the results as they relate to individual persons or subsets of the person sample as they are relevant to the purpose of the analysis.</p>
<p>In our person calibration table, we have included the results for all of the children with non-extreme scores. This includes all of the children in our sample except Child #2. For brevity, we only show the first 6 rows of the person calibration table in this book.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="RS-model.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average rating for persons who did not have extreme scores</span></span>
<span id="cb43-2"><a href="RS-model.html#cb43-2" aria-hidden="true" tabindex="-1"></a>Person_Avg_Rating <span class="ot">&lt;-</span> <span class="fu">apply</span>(person.locations.estimate<span class="sc">$</span>X.ex,<span class="dv">1</span>, mean)</span>
<span id="cb43-3"><a href="RS-model.html#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="RS-model.html#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine person calibration results in a table:</span></span>
<span id="cb43-5"><a href="RS-model.html#cb43-5" aria-hidden="true" tabindex="-1"></a>RSM_Table3 <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(<span class="fu">rownames</span>(person.locations),</span>
<span id="cb43-6"><a href="RS-model.html#cb43-6" aria-hidden="true" tabindex="-1"></a>                          Person_Avg_Rating,</span>
<span id="cb43-7"><a href="RS-model.html#cb43-7" aria-hidden="true" tabindex="-1"></a>                          person.locations<span class="sc">$</span>theta,</span>
<span id="cb43-8"><a href="RS-model.html#cb43-8" aria-hidden="true" tabindex="-1"></a>                          person.locations<span class="sc">$</span>SE,</span>
<span id="cb43-9"><a href="RS-model.html#cb43-9" aria-hidden="true" tabindex="-1"></a>                          person.fit<span class="sc">$</span>outfit_MSE,</span>
<span id="cb43-10"><a href="RS-model.html#cb43-10" aria-hidden="true" tabindex="-1"></a>                          person.fit<span class="sc">$</span>std_outfit,</span>
<span id="cb43-11"><a href="RS-model.html#cb43-11" aria-hidden="true" tabindex="-1"></a>                          person.fit<span class="sc">$</span>infit_MSE,</span>
<span id="cb43-12"><a href="RS-model.html#cb43-12" aria-hidden="true" tabindex="-1"></a>                          person.fit<span class="sc">$</span>std_infit)</span>
<span id="cb43-13"><a href="RS-model.html#cb43-13" aria-hidden="true" tabindex="-1"></a>                          </span>
<span id="cb43-14"><a href="RS-model.html#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(RSM_Table3) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Child ID&quot;</span>, <span class="st">&quot;Average Rating&quot;</span>, <span class="st">&quot;Person Location&quot;</span>,<span class="st">&quot;Person SE&quot;</span>,<span class="st">&quot;Outfit MSE&quot;</span>,<span class="st">&quot;Std. Outfit&quot;</span>, <span class="st">&quot;Infit MSE&quot;</span>,<span class="st">&quot;Std. Infit&quot;</span>)</span>
<span id="cb43-15"><a href="RS-model.html#cb43-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-16"><a href="RS-model.html#cb43-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Round the numeric values (all columns except the first one) to 2 digits:</span></span>
<span id="cb43-17"><a href="RS-model.html#cb43-17" aria-hidden="true" tabindex="-1"></a>RSM_Table3[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(RSM_Table3[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb43-18"><a href="RS-model.html#cb43-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-19"><a href="RS-model.html#cb43-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(RSM_Table3)</span></code></pre></div>
<pre><code>##   Child ID Average Rating Person Location Person SE Outfit MSE Std. Outfit
## 1        1           1.17            1.27      0.34       0.83       -0.45
## 3        3           1.33            1.75      0.35       0.40       -1.99
## 4        4           1.04            0.93      0.34       0.69       -1.03
## 5        5           0.75            0.12      0.35       1.20        0.70
## 6        6           0.92            0.59      0.34       2.36        3.44
## 7        7           1.75            3.31      0.47       1.12        0.41
##   Infit MSE Std. Infit
## 1      0.93      -0.20
## 3      0.43      -2.66
## 4      0.70      -1.26
## 5      0.83      -0.58
## 6      1.57       1.99
## 7      1.80       1.81</code></pre>
</div>
<div id="rsm-analysis-with-mmle-in-tam" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> RSM Analysis with MMLE in <em>TAM</em></h2>
<p>The next section of this chapter includes an illustration of RSM analyses with the <em>Test Analysis Modules</em> or <em>TAM</em> package <span class="citation">(<a href="#ref-TAM" role="doc-biblioref">Robitzsch, Kiefer, and Wu 2021</a>)</span> with Marginal Maximum Likelihood Estimation (MMLE). After this illustration, we also demonstrate the use of <em>TAM</em> to estimate the RSM with Joint Maximum Likelihood Estimation (JMLE). These illustrations use the Liking for Science data set that we described earlier in this chapter.</p>
<p>Except where there are significant differences between the <em>eRm</em> and <em>TAM</em> procedures, we provide fewer details about the analysis procedures and interpretations in this section compared to the first illustration.</p>
<p><strong><em>Prepare for the Analyses</em></strong></p>
<p>To get started with the <em>TAM</em> package, view the citation information, and then install and load it into your R environment using the following code:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="RS-model.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>(<span class="st">&quot;TAM&quot;</span>)</span>
<span id="cb45-2"><a href="RS-model.html#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;TAM&quot;)</span></span>
<span id="cb45-3"><a href="RS-model.html#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;TAM&quot;</span>)</span></code></pre></div>
<p>To facilitate the example analysis, we will also use the <em>WrightMap</em> package <span class="citation">(<a href="#ref-WrightMap" role="doc-biblioref">Irribarra and Freund 2014</a>)</span>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="RS-model.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>(<span class="st">&quot;WrightMap&quot;</span>)</span>
<span id="cb46-2"><a href="RS-model.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;WrightMap&quot;)</span></span>
<span id="cb46-3"><a href="RS-model.html#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;WrightMap&quot;</span>)</span></code></pre></div>
<p>If you have not already imported the Liking for Science data and prepared it for analysis as described earlier in this chapter by dropping item 12 and isolating the response matrix, please do so before continuing with the <em>TAM</em> analyses.</p>
<p><strong><em>Run the Rating Scale Model</em></strong></p>
<p>In order to obtain Rasch-Andrich thresholds (i.e., adjacent-categories thresholds) from our analysis, we need to generate a design matrix for the model that includes specifications for those parameters. We will do this using the <code>designMatrices()</code> function from <em>TAM</em> and save the result in a new object called <code>design.matrix</code>.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="RS-model.html#cb47-1" aria-hidden="true" tabindex="-1"></a>design.matrix <span class="ot">&lt;-</span> <span class="fu">designMatrices</span>(<span class="at">resp=</span>science.responses, <span class="at">modeltype=</span><span class="st">&quot;RSM&quot;</span>, <span class="at">constraint =</span> <span class="st">&quot;items&quot;</span>)<span class="sc">$</span>A</span></code></pre></div>
<p>Now we can run the RSM with our design matrix using the <code>tam.mml()</code> function with several specifications.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="RS-model.html#cb48-1" aria-hidden="true" tabindex="-1"></a>RSM.science_MMLE <span class="ot">&lt;-</span> <span class="fu">tam.mml</span>(science.responses, <span class="at">irtmodel=</span><span class="st">&quot;RSM&quot;</span>, <span class="at">A =</span> design.matrix, <span class="at">constraint =</span> <span class="st">&quot;items&quot;</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<p><strong><em>Overall Model Summary</em></strong></p>
<p>After we run the model, we will request a summary of the model results using the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="RS-model.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RSM.science_MMLE)</span></code></pre></div>
<p>The summary of the RSM output includes details about the number of iterations, global model fit statistics, a summary of the model parameters, and several other statistics.</p>
<p><strong><em>Item Parameters</em></strong></p>
<p>Next, we will examine the overall item difficulty location and rating scale category threshold estimates. First, we need to extract the item location estimates from the model object (<code>RSM.science_MMLE</code>). The item locations are labeled as <em>xsi</em> parameters. We will save the overall item location parameter estimates and their standard errors for our 24 Liking for Science Items by selecting the first 24 rows of the xsi results in an object called <code>items_MMLE</code>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="RS-model.html#cb50-1" aria-hidden="true" tabindex="-1"></a>items_MMLE <span class="ot">&lt;-</span> RSM.science_MMLE<span class="sc">$</span>xsi[<span class="dv">1</span><span class="sc">:</span>(<span class="fu">ncol</span>(science.responses)),]</span></code></pre></div>
<p>Next, we need to find the rating scale category threshold parameter estimates for our rating scale. In our example with the Liking for Science data, our rating scale has three categories, so there are two threshold parameters. The threshold parameters are stored in a table called <code>item_irt</code> within the RSM object. The first threshold is labeled <code>tau.Cat1</code> and the second threshold is labeled <code>tau.Cat2.</code> We can see the values by printing the table to the console.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="RS-model.html#cb51-1" aria-hidden="true" tabindex="-1"></a>RSM.science_MMLE<span class="sc">$</span>item_irt</span></code></pre></div>
<pre><code>##    item alpha         beta  tau.Cat1 tau.Cat2
## 1    i1     1 -0.449669020 -0.785037 0.785037
## 2    i2     1 -0.749690219 -0.785037 0.785037
## 3    i3     1  0.326379571 -0.785037 0.785037
## 4    i4     1  1.582020472 -0.785037 0.785037
## 5    i5     1  2.199070940 -0.785037 0.785037
## 6    i6     1  0.222036480 -0.785037 0.785037
## 7    i7     1  0.974781105 -0.785037 0.785037
## 8    i8     1  1.507112830 -0.785037 0.785037
## 9    i9     1  0.600174068 -0.785037 0.785037
## 10  i10     1 -1.500765124 -0.785037 0.785037
## 11  i11     1 -0.987962778 -0.785037 0.785037
## 12  i13     1 -1.313980081 -0.785037 0.785037
## 13  i14     1  0.326379571 -0.785037 0.785037
## 14  i15     1 -0.532200128 -0.785037 0.785037
## 15  i16     1  0.498022740 -0.785037 0.785037
## 16  i17     1  0.080616226 -0.785037 0.785037
## 17  i18     1 -3.126616101 -0.785037 0.785037
## 18  i19     1 -2.473933212 -0.785037 0.785037
## 19  i20     1  1.658247677 -0.785037 0.785037
## 20  i21     1 -0.889691643 -0.785037 0.785037
## 21  i22     1  0.008649293 -0.785037 0.785037
## 22  i23     1  1.979959819 -0.785037 0.785037
## 23  i24     1 -0.369253269 -0.785037 0.785037
## 24  i25     1  0.430310783 -0.785037 0.785037</code></pre>
<p>The following code extracts the adjacent-categories threshold parameters from the <code>item_irt</code> table and stores them in an object called <code>tau.estimates_MMLE.</code> Because there is only one set of threshold values for the RSM, we can extract the threshold estimates for the first item, and the results are applicable to all of the items in our analysis.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="RS-model.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the number of thresholds as the maximum observed score in the response matrix (be sure the responses begin at category 0):</span></span>
<span id="cb53-2"><a href="RS-model.html#cb53-2" aria-hidden="true" tabindex="-1"></a>n.thresholds <span class="ot">&lt;-</span> <span class="fu">max</span>(science.responses)</span>
<span id="cb53-3"><a href="RS-model.html#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="RS-model.html#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate adjacent-category threshold values:</span></span>
<span id="cb53-5"><a href="RS-model.html#cb53-5" aria-hidden="true" tabindex="-1"></a>tau.estimates_MMLE <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb53-6"><a href="RS-model.html#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="RS-model.html#cb53-7" aria-hidden="true" tabindex="-1"></a>tau.estimates_MMLE <span class="ot">&lt;-</span> RSM.science_MMLE<span class="sc">$</span>item_irt[<span class="dv">1</span>, <span class="fu">c</span>(<span class="dv">4</span><span class="sc">:</span> (<span class="dv">4</span> <span class="sc">+</span> (n.thresholds <span class="sc">-</span> <span class="dv">1</span>)))]</span>
<span id="cb53-8"><a href="RS-model.html#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="RS-model.html#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print adjacent-categories threshold estimates to the console:</span></span>
<span id="cb53-10"><a href="RS-model.html#cb53-10" aria-hidden="true" tabindex="-1"></a>tau.estimates_MMLE</span></code></pre></div>
<pre><code>##    tau.Cat1 tau.Cat2
## 1 -0.785037 0.785037</code></pre>
<p><strong><em>Item Response Functions</em></strong></p>
<p>Next, we will examine rating scale category probability plots for the items in our analysis. For brevity, we have only included plots for the first three items in this book. The specific items to be plotted can be controlled by changing the items included in the <code>items.to.plot</code> object.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="RS-model.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#graphics.off()</span></span>
<span id="cb55-2"><a href="RS-model.html#cb55-2" aria-hidden="true" tabindex="-1"></a>items.to.plot <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb55-3"><a href="RS-model.html#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(RSM.science_MMLE, <span class="at">type=</span><span class="st">&quot;items&quot;</span>, <span class="at">items =</span> items.to.plot)</span></code></pre></div>
<pre><code>## Iteration in WLE/MLE estimation  1   | Maximal change  0.882 
## Iteration in WLE/MLE estimation  2   | Maximal change  0.4971 
## Iteration in WLE/MLE estimation  3   | Maximal change  0.1235 
## Iteration in WLE/MLE estimation  4   | Maximal change  9e-04 
## Iteration in WLE/MLE estimation  5   | Maximal change  0 
## ----
##  WLE Reliability= 0.887</code></pre>
<p><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-35-1.png" width="672" /><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-35-2.png" width="672" /><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-35-3.png" width="672" /></p>
<pre><code>## ....................................................
##  Plots exported in png format into folder:
##  /Users/chenghua/Documents/GitHub/The Rasch Book/Plots</code></pre>
<p>This code generates plots of rating scale category probabilities for each item. These plots have the same interpretation as the rating scale category probability plots that we generated using <em>eRm</em>, where the x-axis is the logit scale that represents the latent variable, the y-axis is the probability for a rating in each category, and individual lines show the conditional probability for a rating in each category.</p>
<p><strong><em>Item Fit</em></strong></p>
<p>Next, we will examine numeric item fit indices using the <code>itemfit()</code> function from <em>TAM</em>. We will save the results in an object called <code>item.fit_MMLE</code> and then view summary statistics for the fit statistics.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="RS-model.html#cb58-1" aria-hidden="true" tabindex="-1"></a>MMLE_fit <span class="ot">&lt;-</span> <span class="fu">tam.fit</span>(RSM.science_MMLE)</span>
<span id="cb58-2"><a href="RS-model.html#cb58-2" aria-hidden="true" tabindex="-1"></a>item.fit_MMLE <span class="ot">&lt;-</span> MMLE_fit<span class="sc">$</span>itemfit</span>
<span id="cb58-3"><a href="RS-model.html#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(item.fit_MMLE)</span></code></pre></div>
<p>As in the dichotomous Rasch model analysis with TAM (see Chapter 2), the <code>tam.fit()</code> function provides mean square error (<em>MSE</em>) and standardized (<em>t</em>) versions of the Outfit and Infit statistics for Rasch models. The <em>Outfit</em> and <em>Infit</em> statistics are the <em>MSE</em> versions and the <code>Outfit_t</code> and <code>Infit_t</code> statistics are the standardized versions of the statistics. <em>TAM</em> also reports a <em>p</em> value for the standardized fit statistics (<code>Outfit_p</code> and <code>Infit_p</code>), along with adjusted significance values (<code>Infit_pholm</code> and <code>Outfit_pholm</code>). Please see Chapter 3 for a detailed consideration of procedures for evaluating item fit in detail, including the use of graphical tools to evaluate item fit.</p>
<p><strong><em>Person Paramters</em></strong></p>
<p>Now we will examine person parameter estimates. With the MMLE procedure in <em>TAM</em>, person parameters are calculated after the item estimates using the <code>tam.wle()</code> function. The following code calculates person parameter estimates and saves them in an object called <code>person.locations_MMLE</code>.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="RS-model.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the tam.wle function to calculate person location parameters:</span></span>
<span id="cb59-2"><a href="RS-model.html#cb59-2" aria-hidden="true" tabindex="-1"></a>person.locations.estimate_MMLE <span class="ot">&lt;-</span> <span class="fu">tam.wle</span>(RSM.science_MMLE)</span></code></pre></div>
<pre><code>## Iteration in WLE/MLE estimation  1   | Maximal change  0.882 
## Iteration in WLE/MLE estimation  2   | Maximal change  0.4971 
## Iteration in WLE/MLE estimation  3   | Maximal change  0.1235 
## Iteration in WLE/MLE estimation  4   | Maximal change  9e-04 
## Iteration in WLE/MLE estimation  5   | Maximal change  0 
## ----
##  WLE Reliability= 0.887</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="RS-model.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store person parameters and their standard errors in a dataframe object:</span></span>
<span id="cb61-2"><a href="RS-model.html#cb61-2" aria-hidden="true" tabindex="-1"></a>person.locations_MMLE <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(person.locations.estimate_MMLE<span class="sc">$</span>theta,</span>
<span id="cb61-3"><a href="RS-model.html#cb61-3" aria-hidden="true" tabindex="-1"></a>                                     person.locations.estimate_MMLE<span class="sc">$</span>error)</span>
<span id="cb61-4"><a href="RS-model.html#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="RS-model.html#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(person.locations_MMLE) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;theta&quot;</span>, <span class="st">&quot;SE&quot;</span>)</span>
<span id="cb61-6"><a href="RS-model.html#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="RS-model.html#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary statistics for person parameters:</span></span>
<span id="cb61-8"><a href="RS-model.html#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(person.locations_MMLE)</span></code></pre></div>
<pre><code>##      theta               SE        
##  Min.   :-1.5815   Min.   :0.3365  
##  1st Qu.: 0.0373   1st Qu.:0.3379  
##  Median : 0.6006   Median :0.3472  
##  Mean   : 0.8280   Mean   :0.3921  
##  3rd Qu.: 1.4708   3rd Qu.:0.3802  
##  Max.   : 5.3850   Max.   :1.4721</code></pre>
<p><strong><em>Person Fit</em></strong></p>
<p>We can evaluate person fit using the <code>tam.personfit()</code> function from TAM. This function uses the model object as an argument and it produces infit and outfit statistics, as well as standardized versions of these statistics, for each person in the response matrix.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="RS-model.html#cb63-1" aria-hidden="true" tabindex="-1"></a>person.fit.results_MMLE <span class="ot">&lt;-</span> <span class="fu">tam.personfit</span>(RSM.science_MMLE)</span>
<span id="cb63-2"><a href="RS-model.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(person.fit.results_MMLE)</span></code></pre></div>
<pre><code>##   outfitPerson     outfitPerson_t      infitPerson      infitPerson_t    
##  Min.   :0.02029   Min.   :-3.08806   Min.   :0.04679   Min.   :-4.0274  
##  1st Qu.:0.52565   1st Qu.:-1.04125   1st Qu.:0.65236   1st Qu.:-1.2797  
##  Median :0.71316   Median :-0.45831   Median :0.83053   Median :-0.4127  
##  Mean   :0.97920   Mean   :-0.04494   Mean   :0.93502   Mean   :-0.3221  
##  3rd Qu.:1.12658   3rd Qu.: 0.50305   3rd Qu.:1.04901   3rd Qu.: 0.2676  
##  Max.   :4.08127   Max.   : 5.28727   Max.   :3.04482   Max.   : 5.1969</code></pre>
<p><strong><em>Wright Map</em></strong></p>
<p>Next, we will create a Wright Map from our model results. This display will provide us with an overview of the distribution of person, item, and threshold parameters. We will create the plot using the <em>WrightMap</em> package function <code>IRT.WrightMap()</code> on the model object (<code>SM.science_MMLE</code>). The following code prepares the parameter estimates and plots the Wright Map using them.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="RS-model.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine item estimates with thresholds:</span></span>
<span id="cb65-2"><a href="RS-model.html#cb65-2" aria-hidden="true" tabindex="-1"></a>n.items <span class="ot">&lt;-</span> <span class="fu">ncol</span>(science.responses)</span>
<span id="cb65-3"><a href="RS-model.html#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="RS-model.html#cb65-4" aria-hidden="true" tabindex="-1"></a>thresholds_MMLE <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">data =</span> <span class="cn">NA</span>, <span class="at">nrow =</span> n.items, <span class="at">ncol =</span> n.thresholds)</span>
<span id="cb65-5"><a href="RS-model.html#cb65-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-6"><a href="RS-model.html#cb65-6" aria-hidden="true" tabindex="-1"></a>tau.estimates_MMLE <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">as.numeric</span>(tau.estimates_MMLE))</span>
<span id="cb65-7"><a href="RS-model.html#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="RS-model.html#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n.thresholds){</span>
<span id="cb65-9"><a href="RS-model.html#cb65-9" aria-hidden="true" tabindex="-1"></a>  items.thresholds <span class="ot">&lt;-</span> items_MMLE <span class="sc">+</span> tau.estimates_MMLE[i]</span>
<span id="cb65-10"><a href="RS-model.html#cb65-10" aria-hidden="true" tabindex="-1"></a>  thresholds_MMLE[, i] <span class="ot">&lt;-</span> items.thresholds[<span class="dv">1</span><span class="sc">:</span>n.items, <span class="dv">1</span>]</span>
<span id="cb65-11"><a href="RS-model.html#cb65-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb65-12"><a href="RS-model.html#cb65-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-13"><a href="RS-model.html#cb65-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the Variable Map</span></span>
<span id="cb65-14"><a href="RS-model.html#cb65-14" aria-hidden="true" tabindex="-1"></a><span class="fu">wrightMap</span>(<span class="at">thetas =</span> person.locations_MMLE<span class="sc">$</span>theta,</span>
<span id="cb65-15"><a href="RS-model.html#cb65-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">thresholds =</span> thresholds_MMLE,</span>
<span id="cb65-16"><a href="RS-model.html#cb65-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">main.title =</span> <span class="st">&quot;Liking for Science Rating Scale Model Wright Map&quot;</span>,</span>
<span id="cb65-17"><a href="RS-model.html#cb65-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">show.thr.lab    =</span> <span class="cn">TRUE</span>, <span class="at">dim.names =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb65-18"><a href="RS-model.html#cb65-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">label.items.rows=</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<pre><code>##             [,1]        [,2]
##  [1,] -1.2347060  0.33536797
##  [2,] -1.5347272  0.03534678
##  [3,] -0.4586574  1.11141657
##  [4,]  0.7969835  2.36705747
##  [5,]  1.4140339  2.98410793
##  [6,] -0.5630005  1.00707347
##  [7,]  0.1897441  1.75981810
##  [8,]  0.7220758  2.29214982
##  [9,] -0.1848629  1.38521106
## [10,] -2.2858021 -0.71572813
## [11,] -1.7729998 -0.20292578
## [12,] -2.0990171 -0.52894309
## [13,] -0.4586574  1.11141657
## [14,] -1.3172371  0.25283687
## [15,] -0.2870143  1.28305973
## [16,] -0.7044208  0.86565322
## [17,] -3.9116531 -2.34157911
## [18,] -3.2589702 -1.68889622
## [19,]  0.8732107  2.44328467
## [20,] -1.6747286 -0.10465465
## [21,] -0.7763877  0.79368629
## [22,]  1.1949228  2.76499681
## [23,] -1.1542903  0.41578373
## [24,] -1.5700740  0.00000000</code></pre>
<p>In this <em>Wright Map</em> display, the results from the RSM analysis of the Liking for Science data are summarized graphically. The figure is organized as follows:</p>
<p>The left panel of the plot shows a histogram of respondent (children) locations on the logit scale that represents the latent variable. Units on the logit scale are shown on the far-right axis of the plot (labeled <em>Logits</em>).</p>
<p>The large central panel of the plot shows the rating scale category threshold estimates specific to each item on the logit scale that represents the latent variable. Light grey diamond shapes show the logit scale location of the threshold estimates for each item, as labeled on the x-axis. Thresholds are labeled using tau symbols followed by an integer that shows the threshold number. In our example, <span class="math inline">\(\tau_1\)</span> is the threshold between rating scale categories <em>x</em> = 0 and <em>x</em> = 1, and <span class="math inline">\(\tau_2\)</span> is the threshold between rating scale categories <em>x</em> = 1 and <em>x</em> = 2.</p>
<p>Even though it is not appropriate to fully interpret item and person locations on the logit scale until there is evidence of acceptable model-data fit, we recommend examining the Wright Map during the preliminary stages of an item analysis to get a general sense of the model results and to identify any potential scoring or data entry errors.</p>
<p>A quick glance at the Wright Map suggests that, on average, the persons are located higher on the logit scale compared to the average item threshold locations. In addition, there appears to be a relatively wide spread of person and item locations on the logit scale, such that the Liking for Science questionnaire appears to be a useful tool for identifying differences in children’s attitudes toward science activities as well as the difficulty to find each of the activities as favorable.</p>
</div>
<div id="rsm-analysis-with-jmle-in-tam" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> RSM Analysis with JMLE in TAM</h2>
<p>In the following section, we provide an illustration of RSM analyses with the <em>Test Analysis Modules</em> or <em>TAM</em> package <span class="citation">(<a href="#ref-TAM" role="doc-biblioref">Robitzsch, Kiefer, and Wu 2021</a>)</span> with Joint Maximum Likelihood Estimation (JMLE). Except where there are significant differences between the MMLE and JMLE procedures, we provide fewer details about the analysis procedures and interpretations compared to the <em>eRm</em> and <em>TAM</em> MMLE illustrations.</p>
<p><strong><em>Prepare for the Analyses</em></strong></p>
<p>Before beginning the JMLE RSM analysis, please ensure that you have installed the <em>TAM</em> and <em>WrightMap</em> packages and loaded them into your working environment. In addition, please ensure that you have imported the Liking for Science data, removed item 12, and isolated the response matrix as described earlier in the chapter.</p>
<p><strong><em>Run the Rating Scale Model</em></strong></p>
<p>We will use the <code>tam.jml()</code> function to run the RSM with JMLE and store the results in an object called <code>RSM.science_JMLE</code>. As with the MMLE procedure, in order to obtain Rasch-Andrich thresholds (i.e., adjacent-categories thresholds), we need to generate a design matrix for the model that includes specifications for those parameters. We will do this using the <code>designMatrices()</code> function from <em>TAM</em> and save the result in a new object called <code>design.matrix</code>.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="RS-model.html#cb67-1" aria-hidden="true" tabindex="-1"></a>design.matrix <span class="ot">&lt;-</span> <span class="fu">designMatrices</span>(<span class="at">resp=</span>science.responses, <span class="at">modeltype=</span><span class="st">&quot;RSM&quot;</span>, <span class="at">constraint =</span> <span class="st">&quot;items&quot;</span>)<span class="sc">$</span>A</span></code></pre></div>
<p>Now we can run the RSM with our design matrix. We have also added a few other specifications to maximize the comparability of the interpretation of the results from this analysis with results from the <span class="citation"><a href="#ref-Winsteps" role="doc-biblioref">Linacre</a> (<a href="#ref-Winsteps" role="doc-biblioref">2020a</a>)</span> and <span class="citation"><a href="#ref-Facets" role="doc-biblioref">Linacre</a> (<a href="#ref-Facets" role="doc-biblioref">2020b</a>)</span> software programs.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="RS-model.html#cb68-1" aria-hidden="true" tabindex="-1"></a>RSM.science_JMLE <span class="ot">&lt;-</span> <span class="fu">tam.jml</span>(science.responses, <span class="at">A =</span> design.matrix, <span class="at">constraint =</span> <span class="st">&quot;items&quot;</span>,<span class="at">control=</span><span class="fu">list</span>(<span class="at">maxiter=</span><span class="dv">500</span>), <span class="at">version=</span><span class="dv">2</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><strong><em>Overall Model Summary</em></strong></p>
<p>After we run the model, we will request a summary of the model results using the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="RS-model.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RSM.science_JMLE)</span></code></pre></div>
<p>The summary of the RSM output includes details about the number of iterations, global model fit statistics, a summary of the model parameters, and several other statistics.</p>
<p><strong><em>Item Parameters</em></strong></p>
<p>Next, we will examine the item difficulty location and rating scale category threshold estimates. First, we need to extract the item location estimates from the model object (<code>RSM.science_MMLE</code>). The item locations are stored in the <code>item</code> table within the model object. The item locations are stored in the <code>xsi.item</code> column of this table. First, we will view the item table by printing it to the console. Then, we will save the overall item location parameter estimates in an object called <code>items_MMLE</code>.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="RS-model.html#cb70-1" aria-hidden="true" tabindex="-1"></a>RSM.science_JMLE<span class="sc">$</span>item</span></code></pre></div>
<pre><code>##     item  N         M      xsi.item AXsi_.Cat1   AXsi_.Cat2 B.Cat1.Dim1
## i1    i1 75 1.4533333 -0.4574934878 -1.2681805 -0.914986976           1
## i2    i2 75 1.5466667 -0.7552041947 -1.5658912 -1.510408389           1
## i3    i3 75 1.1733333  0.3170099599 -0.4936770  0.634019920           1
## i4    i4 75 0.6933333  1.5859579282  0.7752710  3.171915856           1
## i5    i5 75 0.4933333  2.2217139684  1.4110270  4.443427937           1
## i6    i6 75 1.2133333  0.2124921916 -0.5981948  0.424984383           1
## i7    i7 75 0.9200000  0.9689816136  0.1582946  1.937963227           1
## i8    i8 75 0.7200000  1.5095479845  0.6988610  3.019095969           1
## i9    i9 75 1.0666667  0.5913466249 -0.2193404  1.182693250           1
## i10  i10 75 1.7333333 -1.4968099225 -2.3074969 -2.993619845           1
## i11  i11 75 1.6133333 -0.9910288297 -1.8017158 -1.982057659           1
## i13  i13 75 1.6933333 -1.3127959249 -2.1234829 -2.625591850           1
## i14  i14 75 1.1733333  0.3170099599 -0.4936770  0.634019920           1
## i15  i15 75 1.4800000 -0.5394778715 -1.3501648 -1.078955743           1
## i16  i16 75 1.1066667  0.4886897578 -0.3219972  0.977379516           1
## i17  i17 75 1.2666667  0.0710178953 -0.7396691  0.142035791           1
## i18  i18 75 1.9333333 -3.0878980651 -3.8985850 -6.175796130           1
## i19  i19 75 1.8800000 -2.4504761670 -3.2611631 -4.900952334           1
## i20  i20 75 0.6666667  1.6640135967  0.8533266  3.328027193           1
## i21  i21 75 1.5866667 -0.8938071367 -1.7044941 -1.787614273           1
## i22  i22 75 1.2933333 -0.0008840094 -0.8115710 -0.001768019           1
## i23  i23 75 0.5600000  1.9947495520  1.1840626  3.989499104           1
## i24  i24 75 1.4266667 -0.3775422823 -1.1882293 -0.755084565           1
## i25  i25 75 1.1333333  0.4208868590 -0.3898001  0.841773718           1
##     B.Cat2.Dim1
## i1            2
## i2            2
## i3            2
## i4            2
## i5            2
## i6            2
## i7            2
## i8            2
## i9            2
## i10           2
## i11           2
## i13           2
## i14           2
## i15           2
## i16           2
## i17           2
## i18           2
## i19           2
## i20           2
## i21           2
## i22           2
## i23           2
## i24           2
## i25           2</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="RS-model.html#cb72-1" aria-hidden="true" tabindex="-1"></a>items_JMLE <span class="ot">&lt;-</span> RSM.science_JMLE<span class="sc">$</span>item<span class="sc">$</span>xsi.item</span></code></pre></div>
<p>Next, we need to find the adjacent-categories rating scale category threshold parameter estimates for our rating scale. In our example with the Liking for Science data, our rating scale has three categories, so there are two threshold parameters. With the JMLE function in <em>TAM</em>, adjacent-categories threshold values are stored in the <code>item1</code> table within the model object. These threshold estimates are the final values in the <code>xsi</code> column.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="RS-model.html#cb73-1" aria-hidden="true" tabindex="-1"></a>RSM.science_JMLE<span class="sc">$</span>item1</span></code></pre></div>
<pre><code>##    xsi.label xsi.index           xsi     se.xsi
## 1         i1         1 -0.4574934878 0.13927663
## 2         i2         2 -0.7552041947 0.14256938
## 3         i3         3  0.3170099599 0.13420889
## 4         i4         4  1.5859579282 0.13776306
## 5         i5         5  2.2217139684 0.14419747
## 6         i6         6  0.2124921916 0.13457283
## 7         i7         7  0.9689816136 0.13425493
## 8         i8         8  1.5095479845 0.13716421
## 9         i9         9  0.5913466249 0.13374407
## 10       i10        10 -1.4968099225 0.15303171
## 11       i11        11 -0.9910288297 0.14560813
## 12       i13        12 -1.3127959249 0.15022452
## 13       i14        13  0.3170099599 0.13420889
## 14       i15        14 -0.5394778715 0.14011662
## 15       i16        15  0.4886897578 0.13383474
## 16       i17        16  0.0710178953 0.13522854
## 17       i18        17 -3.0878980651 0.17561557
## 18       i19        18 -2.4504761670 0.16762246
## 19       i20        19  1.6640135967 0.13841808
## 20       i21        20 -0.8938071367 0.14431437
## 21       i22        21 -0.0008840094 0.13563297
## 22       i23        22  1.9947495520 0.14163552
## 23       i24        23 -0.3775422823 0.13850953
## 24      Cat1        24 -0.8106869777 0.05342681</code></pre>
<p>With the JMLE function in <em>TAM</em>, the highest threshold parameter is not reported and must be calculated manually. In our example, this is the threshold between category <em>x</em> = 1 and <em>x</em> = 2, and it is the second threshold. The following code calculates the adjacent-categories threshold parameters and stores them in an object called <code>tau.estimates_JMLE</code>:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="RS-model.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the number of thresholds as the maximum observed score in the response matrix (be sure the responses begin at category 0):</span></span>
<span id="cb75-2"><a href="RS-model.html#cb75-2" aria-hidden="true" tabindex="-1"></a>n.thresholds <span class="ot">&lt;-</span> <span class="fu">max</span>(science.responses)</span>
<span id="cb75-3"><a href="RS-model.html#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="RS-model.html#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate adjacent-category threshold values:</span></span>
<span id="cb75-5"><a href="RS-model.html#cb75-5" aria-hidden="true" tabindex="-1"></a>tau.estimates_JMLE <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb75-6"><a href="RS-model.html#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="RS-model.html#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Find all but the final threshold estimate:</span></span>
<span id="cb75-8"><a href="RS-model.html#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(tau <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span> (n.thresholds <span class="sc">-</span> <span class="dv">1</span>)){</span>
<span id="cb75-9"><a href="RS-model.html#cb75-9" aria-hidden="true" tabindex="-1"></a>  tau.estimates_JMLE[tau] <span class="ot">&lt;-</span> RSM.science_JMLE<span class="sc">$</span>item1<span class="sc">$</span>xsi[(<span class="fu">ncol</span>(science.responses) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> tau ]</span>
<span id="cb75-10"><a href="RS-model.html#cb75-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb75-11"><a href="RS-model.html#cb75-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-12"><a href="RS-model.html#cb75-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the final threshold estimate:</span></span>
<span id="cb75-13"><a href="RS-model.html#cb75-13" aria-hidden="true" tabindex="-1"></a>tau.estimates_JMLE[n.thresholds] <span class="ot">&lt;-</span> <span class="sc">-</span>(<span class="fu">sum</span>(tau.estimates_JMLE)) </span>
<span id="cb75-14"><a href="RS-model.html#cb75-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb75-15"><a href="RS-model.html#cb75-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print adjacent-categories threshold estimates to the console:</span></span>
<span id="cb75-16"><a href="RS-model.html#cb75-16" aria-hidden="true" tabindex="-1"></a>tau.estimates_JMLE</span></code></pre></div>
<pre><code>## [1] -0.810687  0.810687</code></pre>
<p><strong><em>Item Response Functions</em></strong></p>
<p>Next, we will examine rating scale category probability plots for the items in our analysis. As before, we only create plots for the first three items wuth this code.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="RS-model.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#graphics.off()</span></span>
<span id="cb77-2"><a href="RS-model.html#cb77-2" aria-hidden="true" tabindex="-1"></a>items.to.plot <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb77-3"><a href="RS-model.html#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(RSM.science_JMLE, <span class="at">type=</span><span class="st">&quot;items&quot;</span>, <span class="at">items =</span> items.to.plot)</span></code></pre></div>
<p><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-46-1.png" width="672" /><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-46-2.png" width="672" /><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-46-3.png" width="672" /></p>
<pre><code>## ....................................................
##  Plots exported in png format into folder:
##  /Users/chenghua/Documents/GitHub/The Rasch Book/Plots</code></pre>
<p>This code generates plots of rating scale category probabilities for each item. These plots have the same interpretation as the rating scale category probability plots presented earlier in this chapter.</p>
<p><strong><em>Item Fit</em></strong></p>
<p>Next, we will examine numeric item fit indices using the <code>tam.fit()</code> function from <em>TAM</em>. We will save the results in an object called <code>item.fit_JMLE</code> and then view summary statistics for the fit statistics.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="RS-model.html#cb79-1" aria-hidden="true" tabindex="-1"></a>JMLE_fit <span class="ot">&lt;-</span> <span class="fu">tam.fit</span>(RSM.science_JMLE)</span>
<span id="cb79-2"><a href="RS-model.html#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="RS-model.html#cb79-3" aria-hidden="true" tabindex="-1"></a>item.fit_JMLE <span class="ot">&lt;-</span> JMLE_fit<span class="sc">$</span>fit.item</span>
<span id="cb79-4"><a href="RS-model.html#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(item.fit_JMLE)</span></code></pre></div>
<pre><code>##      item             outfitItem      outfitItem_t        infitItem     
##  Length:24          Min.   :0.4685   Min.   :-2.43501   Min.   :0.5388  
##  Class :character   1st Qu.:0.6304   1st Qu.:-1.20199   1st Qu.:0.7729  
##  Mode  :character   Median :0.7463   Median :-0.73631   Median :0.8741  
##                     Mean   :0.9979   Mean   : 0.01117   Mean   :1.0083  
##                     3rd Qu.:0.9335   3rd Qu.: 0.08614   3rd Qu.:1.0976  
##                     Max.   :3.3232   Max.   : 7.19795   Max.   :2.3572  
##   infitItem_t     
##  Min.   :-3.6978  
##  1st Qu.:-1.5345  
##  Median :-0.8157  
##  Mean   :-0.3222  
##  3rd Qu.: 0.6672  
##  Max.   : 6.1617</code></pre>
<p>The <code>tam.fit()</code> function provides mean square error (<em>MSE</em>) and standardized (<em>t</em>) versions of the Outfit and Infit statistics for Rasch models for each item estimate.</p>
<p><strong><em>Person Parameters</em></strong></p>
<p>Now we will examine person parameter estimates. With the JMLE procedure in <em>TAM</em>, person parameters are calculated at the same time as the item parameters. This means that we can extract the person parameter estimates from the model object without any additional iterations. The following code calculates person parameter estimates and saves them in an object called <code>person.locations_JMLE.</code></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="RS-model.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store person parameters and their standard errors in a dataframe object:</span></span>
<span id="cb81-2"><a href="RS-model.html#cb81-2" aria-hidden="true" tabindex="-1"></a>person.locations_JMLE <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(RSM.science_JMLE<span class="sc">$</span>theta,</span>
<span id="cb81-3"><a href="RS-model.html#cb81-3" aria-hidden="true" tabindex="-1"></a>                                     RSM.science_JMLE<span class="sc">$</span>errorWLE)</span>
<span id="cb81-4"><a href="RS-model.html#cb81-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-5"><a href="RS-model.html#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(person.locations_JMLE) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;theta&quot;</span>, <span class="st">&quot;SE&quot;</span>)</span>
<span id="cb81-6"><a href="RS-model.html#cb81-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-7"><a href="RS-model.html#cb81-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary statistics for person parameters:</span></span>
<span id="cb81-8"><a href="RS-model.html#cb81-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(person.locations_JMLE)</span></code></pre></div>
<pre><code>##      theta                SE        
##  Min.   :-1.66163   Min.   :0.3420  
##  1st Qu.: 0.03455   1st Qu.:0.3435  
##  Median : 0.62466   Median :0.3530  
##  Mean   : 0.87738   Mean   :0.3940  
##  3rd Qu.: 1.53961   3rd Qu.:0.3859  
##  Max.   : 5.97167   Max.   :1.1795</code></pre>
<p><strong><em>Person Fit</em></strong></p>
<p>Next, we will examine numeric person fit indices using the <code>tam.fit()</code> function from TAM. We will save the results in an object called <code>person.fit_JMLE</code> and then view summary statistics for the fit statistics.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="RS-model.html#cb83-1" aria-hidden="true" tabindex="-1"></a>JMLE_fit <span class="ot">&lt;-</span> <span class="fu">tam.fit</span>(RSM.science_JMLE)</span>
<span id="cb83-2"><a href="RS-model.html#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="RS-model.html#cb83-3" aria-hidden="true" tabindex="-1"></a>person.fit_JMLE <span class="ot">&lt;-</span> JMLE_fit<span class="sc">$</span>fit.person</span>
<span id="cb83-4"><a href="RS-model.html#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(person.fit_JMLE)</span></code></pre></div>
<pre><code>##   outfitPerson     outfitPerson_t     infitPerson      infitPerson_t    
##  Min.   :0.01164   Min.   :-3.1237   Min.   :0.02743   Min.   :-4.0104  
##  1st Qu.:0.54991   1st Qu.:-1.0090   1st Qu.:0.67191   1st Qu.:-1.2205  
##  Median :0.73012   Median :-0.3986   Median :0.89781   Median :-0.2832  
##  Mean   :0.99788   Mean   : 0.0141   Mean   :0.96690   Mean   :-0.2184  
##  3rd Qu.:1.15647   3rd Qu.: 0.6122   3rd Qu.:1.11210   3rd Qu.: 0.4551  
##  Max.   :4.12918   Max.   : 5.3910   Max.   :3.07743   Max.   : 5.2383</code></pre>
<p>The <code>tam.fit()</code> function provides mean square error (<em>MSE</em>) and standardized (<em>t</em>) versions of the Outfit and Infit statistics for Rasch models for each person location estimate.</p>
<p><strong><em>Wright Map</em></strong></p>
<p>Finally, we will create a Wright Map from our model results. This display will provide us with an overview of the distribution of person, item, and threshold parameters. We will create the plot using the <em>WrightMap</em> package function <code>IRT.WrightMap</code> on the model object (<code>RSM.science_JMLE</code>). The following code prepares the parameter estimates and plots the Wright Map using them.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="RS-model.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine item estimates with thresholds:</span></span>
<span id="cb85-2"><a href="RS-model.html#cb85-2" aria-hidden="true" tabindex="-1"></a>n.items <span class="ot">&lt;-</span> <span class="fu">ncol</span>(science.responses)</span>
<span id="cb85-3"><a href="RS-model.html#cb85-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-4"><a href="RS-model.html#cb85-4" aria-hidden="true" tabindex="-1"></a>thresholds_JMLE <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">data =</span> <span class="cn">NA</span>, <span class="at">nrow =</span> n.items, <span class="at">ncol =</span> n.thresholds)</span>
<span id="cb85-5"><a href="RS-model.html#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="RS-model.html#cb85-6" aria-hidden="true" tabindex="-1"></a>tau.estimates_JMLE <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">as.numeric</span>(tau.estimates_JMLE))</span>
<span id="cb85-7"><a href="RS-model.html#cb85-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-8"><a href="RS-model.html#cb85-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n.thresholds){</span>
<span id="cb85-9"><a href="RS-model.html#cb85-9" aria-hidden="true" tabindex="-1"></a>  items.thresholds <span class="ot">&lt;-</span> items_JMLE <span class="sc">+</span> tau.estimates_JMLE[i]</span>
<span id="cb85-10"><a href="RS-model.html#cb85-10" aria-hidden="true" tabindex="-1"></a>  thresholds_JMLE[, i] <span class="ot">&lt;-</span> items.thresholds</span>
<span id="cb85-11"><a href="RS-model.html#cb85-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb85-12"><a href="RS-model.html#cb85-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-13"><a href="RS-model.html#cb85-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the Wright Map</span></span>
<span id="cb85-14"><a href="RS-model.html#cb85-14" aria-hidden="true" tabindex="-1"></a><span class="fu">wrightMap</span>(<span class="at">thetas =</span> person.locations_JMLE<span class="sc">$</span>theta,</span>
<span id="cb85-15"><a href="RS-model.html#cb85-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">thresholds =</span> thresholds_JMLE,</span>
<span id="cb85-16"><a href="RS-model.html#cb85-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">main.title =</span> <span class="st">&quot;Liking for Science Rating Scale Model Wright Map: JMLE&quot;</span>,</span>
<span id="cb85-17"><a href="RS-model.html#cb85-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">show.thr.lab    =</span> <span class="cn">TRUE</span>, <span class="at">dim.names =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb85-18"><a href="RS-model.html#cb85-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">label.items.rows=</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="The-Rasch-Book_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<pre><code>##             [,1]        [,2]
##  [1,] -1.2681805  0.35319349
##  [2,] -1.5658912  0.05548278
##  [3,] -0.4936770  1.12769694
##  [4,]  0.7752710  2.39664491
##  [5,]  1.4110270  3.03240095
##  [6,] -0.5981948  1.02317917
##  [7,]  0.1582946  1.77966859
##  [8,]  0.6988610  2.32023496
##  [9,] -0.2193404  1.40203360
## [10,] -2.3074969 -0.68612294
## [11,] -1.8017158 -0.18034185
## [12,] -2.1234829 -0.50210895
## [13,] -0.4936770  1.12769694
## [14,] -1.3501648  0.27120911
## [15,] -0.3219972  1.29937674
## [16,] -0.7396691  0.88170487
## [17,] -3.8985850 -2.27721109
## [18,] -3.2611631 -1.63978919
## [19,]  0.8533266  2.47470057
## [20,] -1.7044941 -0.08312016
## [21,] -0.8115710  0.80980297
## [22,]  1.1840626  2.80543653
## [23,] -1.1882293  0.43314470
## [24,] -0.3898001  1.23157384</code></pre>
<p>In this <em>Wright Map</em> display, the results from the RSM analysis of the Liking for Science data are summarized graphically. The figure is organized in the same way as we described for the MMLE RSM analysis earlier in this chapter.</p>
</div>
<div id="example-results-section-1" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Example Results Section</h2>
<p>Table 1 presents a summary of the results from the analysis of the Liking for Science data <span class="citation">(<a href="#ref-RS_analysis" role="doc-biblioref">Wright and Masters 1982</a>)</span> using the Rating Scale Model (RSM) <span class="citation">(<a href="#ref-Rating_Form" role="doc-biblioref">Andrich 1978</a>)</span>. One item was excluded (item 12) because the responses to this item did not include any observations in the lowest rating scale category (<em>x</em> = 0). In addition, one child was excluded from the analysis (Child #2), who gave extreme responses to all of the items (<em>x</em> = 2).</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="RS-model.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print Table 1:</span></span>
<span id="cb87-2"><a href="RS-model.html#cb87-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb87-3"><a href="RS-model.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  RSM_Table1, <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb87-4"><a href="RS-model.html#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Model Summary Table&#39;</span></span>
<span id="cb87-5"><a href="RS-model.html#cb87-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-51">Table 4.1: </span>Model Summary Table</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Statistic</th>
<th align="right">Items</th>
<th align="right">Persons</th>
<th align="right">NA</th>
<th align="right">NA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">X</td>
<td align="left">Logit Scale Location Mean</td>
<td align="right">0.00</td>
<td align="right">1.57</td>
<td align="right">1.57</td>
<td align="right">1.57</td>
</tr>
<tr class="even">
<td align="left">X.1</td>
<td align="left">Logit Scale Location SD</td>
<td align="right">1.33</td>
<td align="right">1.18</td>
<td align="right">1.18</td>
<td align="right">1.18</td>
</tr>
<tr class="odd">
<td align="left">X.2</td>
<td align="left">Standard Error Mean</td>
<td align="right">0.22</td>
<td align="right">0.38</td>
<td align="right">0.38</td>
<td align="right">0.38</td>
</tr>
<tr class="even">
<td align="left">X.3</td>
<td align="left">Standard Error SD</td>
<td align="right">0.06</td>
<td align="right">0.10</td>
<td align="right">0.10</td>
<td align="right">0.10</td>
</tr>
<tr class="odd">
<td align="left">X.4</td>
<td align="left">Outfit MSE Mean</td>
<td align="right">1.05</td>
<td align="right">1.05</td>
<td align="right">1.05</td>
<td align="right">1.05</td>
</tr>
<tr class="even">
<td align="left">X.5</td>
<td align="left">Outfit MSE SD</td>
<td align="right">0.82</td>
<td align="right">0.99</td>
<td align="right">0.99</td>
<td align="right">0.99</td>
</tr>
<tr class="odd">
<td align="left">X.6</td>
<td align="left">Infit MSE Mean</td>
<td align="right">1.00</td>
<td align="right">0.96</td>
<td align="right">0.96</td>
<td align="right">0.96</td>
</tr>
<tr class="even">
<td align="left">X.7</td>
<td align="left">Infit MSE SD</td>
<td align="right">0.45</td>
<td align="right">0.49</td>
<td align="right">0.49</td>
<td align="right">0.49</td>
</tr>
<tr class="odd">
<td align="left">X.8</td>
<td align="left">Std. Outfit Mean</td>
<td align="right">-0.18</td>
<td align="right">0.02</td>
<td align="right">0.02</td>
<td align="right">0.02</td>
</tr>
<tr class="even">
<td align="left">X.9</td>
<td align="left">Std. Outfit SD</td>
<td align="right">2.77</td>
<td align="right">1.85</td>
<td align="right">1.85</td>
<td align="right">1.85</td>
</tr>
<tr class="odd">
<td align="left">X.10</td>
<td align="left">Std. Infit Mean</td>
<td align="right">-0.42</td>
<td align="right">-0.28</td>
<td align="right">-0.28</td>
<td align="right">-0.28</td>
</tr>
<tr class="even">
<td align="left">X.11</td>
<td align="left">Std. Infit SD</td>
<td align="right">2.35</td>
<td align="right">1.63</td>
<td align="right">1.63</td>
<td align="right">1.63</td>
</tr>
<tr class="odd">
<td align="left">item.separation.reliability</td>
<td align="left">Separation.reliability</td>
<td align="right">1.00</td>
<td align="right">0.89</td>
<td align="right">1.39</td>
<td align="right">0.16</td>
</tr>
</tbody>
</table>
<p>Specifically, Table 1 summarizes the calibration of the children with non-extreme responses (<em>N</em> = 74) and the items (<em>N</em> = 24) using average logit-scale calibrations, standard errors, and model-data fit statistics. Examination of the results indicates that, on average, the students were located higher on the logit scale (<em>M</em> = 1.57,<em>SD</em> = 1.18), compared to items, whose locations were centered at zero logits (<em>M</em> = 0.00, <em>SD</em> = 1.33). This finding suggests that the items were relatively easy to endorse among the sample of children who participated in this study. The average values of the Standard Error (<em>SE</em>) were comparable for children (<em>M</em> = 0.38) and items (<em>M</em> = 0.22). Average values of model-data fit statistics indicate overall adequate fit to the model, with average Infit and Outfit mean square error (MSE) statistics around 1.00, and average standardized Infit and Outfit statistics near the expected value of 0.00 when data fit the model. However, there was some variability in item fit and person fit, as indicated by relatively large standard errors for the fit statistics. Additional investigation into item fit and person fit is warranted.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="RS-model.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print Table 2:</span></span>
<span id="cb88-2"><a href="RS-model.html#cb88-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb88-3"><a href="RS-model.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  RSM_Table2, <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb88-4"><a href="RS-model.html#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Item Calibration&#39;</span></span>
<span id="cb88-5"><a href="RS-model.html#cb88-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-52">Table 4.2: </span>Item Calibration</caption>
<colgroup>
<col width="4%" />
<col width="8%" />
<col width="16%" />
<col width="15%" />
<col width="8%" />
<col width="11%" />
<col width="12%" />
<col width="10%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Task ID</th>
<th align="right">Average Rating</th>
<th align="right">Item Location</th>
<th align="right">Item SE</th>
<th align="right">Outfit MSE</th>
<th align="right">Std. Outfit</th>
<th align="right">Infit MSE</th>
<th align="right">Std. Infit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">i5</td>
<td align="right">5</td>
<td align="right">0.49</td>
<td align="right">2.21</td>
<td align="right">0.18</td>
<td align="right">3.29</td>
<td align="right">6.77</td>
<td align="right">2.20</td>
<td align="right">5.31</td>
</tr>
<tr class="even">
<td align="left">i23</td>
<td align="right">22</td>
<td align="right">0.56</td>
<td align="right">1.98</td>
<td align="right">0.20</td>
<td align="right">3.77</td>
<td align="right">8.42</td>
<td align="right">2.32</td>
<td align="right">5.99</td>
</tr>
<tr class="odd">
<td align="left">i20</td>
<td align="right">19</td>
<td align="right">0.67</td>
<td align="right">1.66</td>
<td align="right">0.22</td>
<td align="right">1.67</td>
<td align="right">3.16</td>
<td align="right">1.27</td>
<td align="right">1.66</td>
</tr>
<tr class="even">
<td align="left">i4</td>
<td align="right">4</td>
<td align="right">0.69</td>
<td align="right">1.58</td>
<td align="right">0.22</td>
<td align="right">0.86</td>
<td align="right">-0.78</td>
<td align="right">0.85</td>
<td align="right">-0.99</td>
</tr>
<tr class="odd">
<td align="left">i8</td>
<td align="right">8</td>
<td align="right">0.72</td>
<td align="right">1.50</td>
<td align="right">0.18</td>
<td align="right">1.15</td>
<td align="right">0.87</td>
<td align="right">1.06</td>
<td align="right">0.42</td>
</tr>
<tr class="even">
<td align="left">i7</td>
<td align="right">7</td>
<td align="right">0.92</td>
<td align="right">0.97</td>
<td align="right">0.20</td>
<td align="right">0.97</td>
<td align="right">-0.15</td>
<td align="right">0.94</td>
<td align="right">-0.42</td>
</tr>
<tr class="odd">
<td align="left">i9</td>
<td align="right">9</td>
<td align="right">1.07</td>
<td align="right">0.59</td>
<td align="right">0.25</td>
<td align="right">1.13</td>
<td align="right">0.81</td>
<td align="right">1.14</td>
<td align="right">0.99</td>
</tr>
<tr class="even">
<td align="left">i16</td>
<td align="right">15</td>
<td align="right">1.11</td>
<td align="right">0.49</td>
<td align="right">0.19</td>
<td align="right">0.90</td>
<td align="right">-0.53</td>
<td align="right">0.92</td>
<td align="right">-0.53</td>
</tr>
<tr class="odd">
<td align="left">i25</td>
<td align="right">24</td>
<td align="right">1.13</td>
<td align="right">0.42</td>
<td align="right">0.13</td>
<td align="right">0.71</td>
<td align="right">-1.83</td>
<td align="right">0.76</td>
<td align="right">-1.82</td>
</tr>
<tr class="even">
<td align="left">i3</td>
<td align="right">3</td>
<td align="right">1.17</td>
<td align="right">0.32</td>
<td align="right">0.20</td>
<td align="right">0.52</td>
<td align="right">-3.22</td>
<td align="right">0.55</td>
<td align="right">-3.81</td>
</tr>
<tr class="odd">
<td align="left">i14</td>
<td align="right">13</td>
<td align="right">1.17</td>
<td align="right">0.32</td>
<td align="right">0.20</td>
<td align="right">0.72</td>
<td align="right">-1.65</td>
<td align="right">0.79</td>
<td align="right">-1.58</td>
</tr>
<tr class="even">
<td align="left">i6</td>
<td align="right">6</td>
<td align="right">1.21</td>
<td align="right">0.21</td>
<td align="right">0.19</td>
<td align="right">0.72</td>
<td align="right">-1.60</td>
<td align="right">0.78</td>
<td align="right">-1.67</td>
</tr>
<tr class="odd">
<td align="left">i17</td>
<td align="right">16</td>
<td align="right">1.27</td>
<td align="right">0.07</td>
<td align="right">0.45</td>
<td align="right">0.57</td>
<td align="right">-2.56</td>
<td align="right">0.63</td>
<td align="right">-2.92</td>
</tr>
<tr class="even">
<td align="left">i22</td>
<td align="right">21</td>
<td align="right">1.29</td>
<td align="right">0.00</td>
<td align="right">0.21</td>
<td align="right">0.72</td>
<td align="right">-1.50</td>
<td align="right">0.80</td>
<td align="right">-1.41</td>
</tr>
<tr class="odd">
<td align="left">i24</td>
<td align="right">23</td>
<td align="right">1.43</td>
<td align="right">-0.37</td>
<td align="right">0.18</td>
<td align="right">0.77</td>
<td align="right">-1.04</td>
<td align="right">0.87</td>
<td align="right">-0.83</td>
</tr>
<tr class="even">
<td align="left">i1</td>
<td align="right">1</td>
<td align="right">1.45</td>
<td align="right">-0.45</td>
<td align="right">0.21</td>
<td align="right">0.48</td>
<td align="right">-2.68</td>
<td align="right">0.53</td>
<td align="right">-3.65</td>
</tr>
<tr class="odd">
<td align="left">i15</td>
<td align="right">14</td>
<td align="right">1.48</td>
<td align="right">-0.53</td>
<td align="right">0.18</td>
<td align="right">0.62</td>
<td align="right">-1.71</td>
<td align="right">0.76</td>
<td align="right">-1.64</td>
</tr>
<tr class="even">
<td align="left">i2</td>
<td align="right">2</td>
<td align="right">1.55</td>
<td align="right">-0.75</td>
<td align="right">0.18</td>
<td align="right">0.71</td>
<td align="right">-1.12</td>
<td align="right">0.90</td>
<td align="right">-0.55</td>
</tr>
<tr class="odd">
<td align="left">i21</td>
<td align="right">20</td>
<td align="right">1.59</td>
<td align="right">-0.89</td>
<td align="right">0.19</td>
<td align="right">0.64</td>
<td align="right">-1.35</td>
<td align="right">0.82</td>
<td align="right">-1.03</td>
</tr>
<tr class="even">
<td align="left">i11</td>
<td align="right">11</td>
<td align="right">1.61</td>
<td align="right">-0.98</td>
<td align="right">0.24</td>
<td align="right">0.47</td>
<td align="right">-2.10</td>
<td align="right">0.60</td>
<td align="right">-2.64</td>
</tr>
<tr class="odd">
<td align="left">i13</td>
<td align="right">12</td>
<td align="right">1.69</td>
<td align="right">-1.31</td>
<td align="right">0.18</td>
<td align="right">0.93</td>
<td align="right">-0.09</td>
<td align="right">1.20</td>
<td align="right">1.02</td>
</tr>
<tr class="even">
<td align="left">i10</td>
<td align="right">10</td>
<td align="right">1.73</td>
<td align="right">-1.49</td>
<td align="right">0.22</td>
<td align="right">0.56</td>
<td align="right">-1.23</td>
<td align="right">0.77</td>
<td align="right">-1.14</td>
</tr>
<tr class="odd">
<td align="left">i19</td>
<td align="right">18</td>
<td align="right">1.88</td>
<td align="right">-2.45</td>
<td align="right">0.20</td>
<td align="right">1.03</td>
<td align="right">0.25</td>
<td align="right">1.04</td>
<td align="right">0.23</td>
</tr>
<tr class="even">
<td align="left">i18</td>
<td align="right">17</td>
<td align="right">1.93</td>
<td align="right">-3.10</td>
<td align="right">0.35</td>
<td align="right">1.26</td>
<td align="right">0.56</td>
<td align="right">1.43</td>
<td align="right">1.05</td>
</tr>
</tbody>
</table>
<p>Table 2 includes detailed results for the 24 items included in the analysis, where items are ordered by their overall logit-scale location (i.e., item difficulty) from high (easy to endorse) to low (difficult to endorse).. For each item, the average rating is presented, followed by the overall logit-scale location (<em>δ</em>), SE, and model-data fit statistics. Examination of these results indicates that Item 5 was the most difficult to endorse (<em>Average Rating = 0.49; </em>δ* = 2.21 ; <em>SE</em> = 0.18), followed by Item 23 (<em>Average Rating</em> = 0.56; <em>δ</em> = 1.98; <em>SE</em> = 0.20). The easiest item to endorse was Item 18 (<em>Average Rating</em> = 1.93; <em>δ</em> = -3.10; <em>SE</em> = 0.35).</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="RS-model.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print Table 3:</span></span>
<span id="cb89-2"><a href="RS-model.html#cb89-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb89-3"><a href="RS-model.html#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(RSM_Table3,<span class="dv">10</span>), <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb89-4"><a href="RS-model.html#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Person Calibration&#39;</span></span>
<span id="cb89-5"><a href="RS-model.html#cb89-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-53">Table 4.3: </span>Person Calibration</caption>
<colgroup>
<col width="3%" />
<col width="9%" />
<col width="15%" />
<col width="16%" />
<col width="10%" />
<col width="11%" />
<col width="12%" />
<col width="10%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Child ID</th>
<th align="right">Average Rating</th>
<th align="right">Person Location</th>
<th align="right">Person SE</th>
<th align="right">Outfit MSE</th>
<th align="right">Std. Outfit</th>
<th align="right">Infit MSE</th>
<th align="right">Std. Infit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">1</td>
<td align="right">1.17</td>
<td align="right">1.27</td>
<td align="right">0.34</td>
<td align="right">0.83</td>
<td align="right">-0.45</td>
<td align="right">0.93</td>
<td align="right">-0.20</td>
</tr>
<tr class="even">
<td align="left">3</td>
<td align="left">3</td>
<td align="right">1.33</td>
<td align="right">1.75</td>
<td align="right">0.35</td>
<td align="right">0.40</td>
<td align="right">-1.99</td>
<td align="right">0.43</td>
<td align="right">-2.66</td>
</tr>
<tr class="odd">
<td align="left">4</td>
<td align="left">4</td>
<td align="right">1.04</td>
<td align="right">0.93</td>
<td align="right">0.34</td>
<td align="right">0.69</td>
<td align="right">-1.03</td>
<td align="right">0.70</td>
<td align="right">-1.26</td>
</tr>
<tr class="even">
<td align="left">5</td>
<td align="left">5</td>
<td align="right">0.75</td>
<td align="right">0.12</td>
<td align="right">0.35</td>
<td align="right">1.20</td>
<td align="right">0.70</td>
<td align="right">0.83</td>
<td align="right">-0.58</td>
</tr>
<tr class="odd">
<td align="left">6</td>
<td align="left">6</td>
<td align="right">0.92</td>
<td align="right">0.59</td>
<td align="right">0.34</td>
<td align="right">2.36</td>
<td align="right">3.44</td>
<td align="right">1.57</td>
<td align="right">1.99</td>
</tr>
<tr class="even">
<td align="left">7</td>
<td align="left">7</td>
<td align="right">1.75</td>
<td align="right">3.31</td>
<td align="right">0.47</td>
<td align="right">1.12</td>
<td align="right">0.41</td>
<td align="right">1.80</td>
<td align="right">1.81</td>
</tr>
<tr class="odd">
<td align="left">8</td>
<td align="left">8</td>
<td align="right">1.29</td>
<td align="right">1.62</td>
<td align="right">0.35</td>
<td align="right">0.83</td>
<td align="right">-0.39</td>
<td align="right">0.98</td>
<td align="right">0.03</td>
</tr>
<tr class="even">
<td align="left">9</td>
<td align="left">9</td>
<td align="right">0.92</td>
<td align="right">0.59</td>
<td align="right">0.34</td>
<td align="right">1.80</td>
<td align="right">2.28</td>
<td align="right">1.37</td>
<td align="right">1.37</td>
</tr>
<tr class="odd">
<td align="left">10</td>
<td align="left">10</td>
<td align="right">1.08</td>
<td align="right">1.04</td>
<td align="right">0.34</td>
<td align="right">0.65</td>
<td align="right">-1.19</td>
<td align="right">0.70</td>
<td align="right">-1.25</td>
</tr>
<tr class="even">
<td align="left">11</td>
<td align="left">11</td>
<td align="right">1.38</td>
<td align="right">1.87</td>
<td align="right">0.36</td>
<td align="right">0.79</td>
<td align="right">-0.43</td>
<td align="right">0.97</td>
<td align="right">-0.01</td>
</tr>
</tbody>
</table>
<p>Table 3 includes detailed results for first 10 children who participated in the Liking for Science survey. For each child, the average rating is presented, followed by their logit-scale location estimate (<em>θ</em>), <em>SE</em>, and model-data fit statistics.</p>
<p>Figure 1</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="RS-model.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the variable-Map</span></span>
<span id="cb90-2"><a href="RS-model.html#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">graphics.off</span>()</span>
<span id="cb90-3"><a href="RS-model.html#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPImap</span>(RSM.science, <span class="at">main =</span> <span class="st">&quot;Liking for Science Rating Scale Model Wright Map&quot;</span>, <span class="at">sorted =</span> <span class="cn">TRUE</span>, <span class="at">irug =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Figure 1 illustrates the calibrations of the children and items on the logit scale that represents the latent variable. The calibrations shown in this figure correspond to the results presented in Table 2 and Table 3 for items and children, respectively.Starting at the bottom of the figure, the horizontal axis (labeled <em>Latent Dimension</em>) is the logit scale that represents the latent variable. Lower numbers on this scale indicate less-favorable attitudes toward science activities, and higher numbers indicate more-favorable attitudes toward science activities. The central panel of the figure shows item difficulty locations on the logit scale for the 24 Liking for Science items included in the analysis; the y-axis for this panel shows the item labels. The items are ordered according to their difficulty order, as estimated with the RSM. Easier-to-endorse items appear at the top of the figure, and harder-to-endorse items appear at the bottom of the figure; item labels are shown on the y-axis. For each item, a solid circle plotting symbol shows the overall location estimate. This solid circle symbol is connected to two open-circle symbols that show the locations of the rating scale category thresholds. Each threshold is labeled with a “1” to indicate the threshold between rating scale category <em>x</em> = 0 and <em>x</em> = 1, or a “2” to indicate the threshold between rating scale category <em>x</em> = 1 and <em>x</em> = 2. Examination of the item locations reveals that the threshold locations were ordered as expected, with <span class="math inline">\(\tau_1\)</span> located lower on the logit scale (<span class="math inline">\(\tau_1\)</span> = -0.78) compared to the location estimate for <span class="math inline">\(\tau_2\)</span> (<span class="math inline">\(\tau_2\)</span> = 0.78). The upper panel of the figure shows a histogram of person (in this case, children) location estimates on the logit scale.</p>
</div>
<div id="exercise-2" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Exercise</h2>
<p>Please use the <em>eRm</em> or <em>TAM</em> package to estimate item, threshold, and person locations with the RSM for the Exercise 4 data. The Exercise 4 data include responses from 500 participants to an attitude survey that includes 20 items with a 5-category rating scale. Then, try writing a results section similar to the example in this chapter based on your findings.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Rating_Form" class="csl-entry">
Andrich, David. 1978. <span>“A Rating Formulation for Ordered Response Categories.”</span> <em>Psychometrika</em> 43 (4): 561–73. https://doi.org/<a href="https://doi.org/10.1007/bf02293814">https://doi.org/10.1007/bf02293814</a>.
</div>
<div id="ref-Prob_PM" class="csl-entry">
———. 2015. <span>“The Problem with the Step Metaphor for Polytomous Models for Ordinal Assessments.”</span> <em>Educational Measurement: Issues and Practice</em> 34 (2): 8–14. https://doi.org/<a href="https://doi.org/10.1111/emip.12074">https://doi.org/10.1111/emip.12074</a>.
</div>
<div id="ref-WrightMap" class="csl-entry">
Irribarra, David Torres, and Rebecca Freund. 2014. <em>Wright Map: IRT Item-Person Map with ConQuest Integration</em>. <a href="http://github.com/david-ti/wrightmap">http://github.com/david-ti/wrightmap</a>.
</div>
<div id="ref-Winsteps" class="csl-entry">
Linacre, John Michael. 2020a. <em>A User’s Guide to WINSTEPS MINISTEP Rasch-Model Computer Programs</em> (version 4.7.0). <a href="https://www.winsteps.com/winman/copyright.htm">https://www.winsteps.com/winman/copyright.htm</a>.
</div>
<div id="ref-Facets" class="csl-entry">
———. 2020b. <em>Facets Computer Program for Many-Facet Rasch Measurement</em> (version 3.83.4). Beaverton, Oregon. <a href="https://Winsteps.com">Winsteps.com</a>.
</div>
<div id="ref-eRm" class="csl-entry">
Mair, Patrick, Reinhold Hatzinger, and Marco Johannes Maier. 2021. <em><span class="nocase">eRm: Extended Rasch Modeling</span></em>. <a href="https://cran.r-project.org/package=eRm">https://cran.r-project.org/package=eRm</a>.
</div>
<div id="ref-Conceptual_notes" class="csl-entry">
Mellenbergh, Gideon J. 1995. <span>“Conceptual Notes on Models for Discrete Polytomous Item Responses.”</span> <em>Applied Psychological Measurement</em> 19 (1): 91–100. https://doi.org/<a href="https://doi.org/10.1177/014662169501900110">https://doi.org/10.1177/014662169501900110</a>.
</div>
<div id="ref-R-base" class="csl-entry">
R Core Team. 2019. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-TAM" class="csl-entry">
Robitzsch, Alexander, Thomas Kiefer, and Margaret Wu. 2021. <em>TAM: Test Analysis Modules</em>. <a href="https://CRAN.R-project.org/package=TAM">https://CRAN.R-project.org/package=TAM</a>.
</div>
<div id="ref-RS_analysis" class="csl-entry">
Wright, Benjamin D., and Geofferey N. Masters. 1982. <em>Rating Scale Analysis</em>. MESA Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="MD-fit.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="PC-model.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/huacheng1985/bookdown-demo/edit/master/04-RS_model.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["The Rasch Book.pdf", "The Rasch Book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
